import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'fr' | 'de' | 'lb' | 'pt';

export const LANGUAGES_LIST: { code: Language; name: string; flag: string }[] = [
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'lb', name: 'Lëtzebuergesch', flag: '🇱🇺' }
];

interface Translations {
  // General
  welcome: string;
  findPro: string;
  searchPlaceholder: string;
  login: string;
  logout: string;
  signup: string;
  profile: string;
  messages: string;
  notifications: string;
  settings: string;

  // Job Status
  OPEN: string;
  IN_PROGRESS: string;
  COMPLETED: string;
  CANCELLED: string;

  // Tabs
  liveMarket: string;
  myRequests: string;
  historyTab: string;
  teamTab: string;

  // Actions
  postJob: string;
  viewDetails: string;
  accept: string;
  decline: string;
  hire: string;

  // Categories
  total: string;
  cleaning: string;
  moving: string;
  plumbing: string;
  electrical: string;
  painting: string;
  gardening: string;

  // Pro Dashboard
  opportunities: string;
  scanningJobs: string;
  financialErp: string;
  financialPerformance: string;
  addTransaction: string;
  exportReport: string;
  breakdown: string;
  noJobsPeriod: string;
  manageTeam: string;
  manageTeamDesc: string;
  addMember: string;
  staffAdded: string;
  saveEmployee: string;
  roleTitle: string;
  active: string;
  inactive: string;
  fullName: string;
  emailLogin: string;

  // Invoice
  invBillTo: string;
  invDate: string;
  invDue: string;
  invDesc: string;
  invQty: string;
  invRate: string;
  invTotal: string;
  invSubtotal: string;
  invVatAmt: string;
  invTotalDue: string;
  invFooter: string;

  // New
  detailsLabel: string;
  photosOptional: string;
  yourOffer: string;
  cancel: string;
  saveChanges: string;
  today: string;
  yesterday: string;
  noHistory: string;
  confirmDelete: string;
  noActiveRequests: string;
  signIn: string;
  welcomeSubtitle: string;
  loginWithEmail: string;
  loginWithPhone: string;
  email: string;
  phoneLabel: string;
  password: string;
  forgotPassword: string;
  dontHaveAccount: string;
  signUp: string;
  createAccount: string;
  loggedAs: string;
  dashboard: string;
  whatNeed: string;
  messagesTab: string;
  manageRequests: string;
  createFirstRequest: string;
  editRequest: string;
  deleteRequest: string;
  goToMarket: string;
  waitingClient: string;
  acceptAndChat: string;
  noRequestsDesc: string;
  favoritesTab: string;
  noFavorites: string;
  instaPortfolio: string;
  clientRole: string;
  reliableClient: string;
  requestsMade: string;
  paymentRate: string;
  speaks: string;
  serviceLocation: string;
  openMaps: string;
  verifiedBadge: string;
  jobs: string;
  onlinePresence: string;
  businessHours: string;
  bio: string;
  serviceTimeline: string;
  contactInfo: string;
  removeFromFavorites: string;
  addToFavorites: string;
  unblockContact: string;
  blockContact: string;
  hireNow: string;
  imClient: string;
  imPro: string;
  back: string;
  noCompany: string;
  personalDetails: string;
  businessDetails: string;
  servicesAndScope: string;
  licenseDetails: string;
  financialPlan: string;
  reviewDetails: string;
  stepIndicator: string;
  confirmPasswordLabel: string;
  cnsNumber: string;
  street: string;
  number: string;
  floor: string;
  residence: string;
  elevator: string;
  parking: string;
  addAddress: string;
  postalCode: string;
  locality: string;
  idUpload: string;
  attached: string;
  independant: string;
  societe: string;
  companyName: string;
  tvaNumber: string;
  rcsNumber: string;
  selectServices: string;
  selectServicesDesc: string;
  licenseInfo: string;
  licenseNum: string;
  licenseExpiry: string;
  uploadPdfLabel: string;
  licenseUploaded: string;
  planSelect: string;
  founderOffer: string;
  premiumPlan: string;
  lifetimeAccess: string;
  benefitSite: string;
  benefitPriority: string;
  benefitFees: string;
  benefitSupport: string;
  benefitBadge: string;
  durationLabel: string;
  freeForever: string;
  basicPlan: string;
  basicDesc: string;
  payoutDetails: string;
  iban: string;
  accHolder: string;
  paymentMethod: string;
  paymentValidation: string;
  expiryDate: string;
  cvc: string;
  cardHolder: string;
  websiteReady: string;
  websiteDesc: string;
  visitSite: string;
  generatedFor: string;
  summaryServices: string;
  summaryPlan: string;
  summaryIban: string;
  declaration: string;
  finish: string;
  next: string;
  welcomeBack: string;
  personalInfo: string;
  manageIdentity: string;
  languages: string;
  addressLogistics: string;
  smartAddress: string;
  houseNumber: string;
  security: string;
  blockedUsers: string;
  noBlockedUsers: string;
  smartReply: string;
  smartReplyDesc: string;
  enableAutoReply: string;
  activationTime: string;
  immediate: string;
  mins5: string;
  mins15: string;
  botPersonality: string;
  agilityMode: string;
  agilityDesc: string;
  dataMode: string;
  dataDesc: string;
  customMode: string;
  customDesc: string;
  yourMessage: string;
  botMessageCustomDefault: string;
  preview: string;
  botMessageAgility: string;
  botMessageData: string;
  botMsgFooter: string;
  siteStatus: string;
  online: string;
  offline: string;
  shareWhatsapp: string;
  appearance: string;
  selectTheme: string;
  accentColor: string;
  previewSite: string;
  siteInfo: string;
  siteInfoDesc: string;
  visitExternal: string;
  companyDesc: string;
  cantEditHelp: string;
  workingDays: string;
  openingTime: string;
  closingTime: string;
  subscription: string;
  currentPlan: string;
  activePlan: string;
  upgradeBtn: string;
  paymentCard: string;
  legalForm: string;
  banking: string;
  logisticsNote: string;
  luxNoteDesc: string;
  clientRoleDesc: string;
  reliableClientDesc: string;
  myWebsite: string;
  chatSettings: string;
  themeModern: string;
  themeClassic: string;
  themeBold: string;
  themeMinimal: string;
  companyData: string;
  companyLocation: string;
  staffRestriction: string;
  staffRestrictionDesc: string;
  staffDashboard: string;
  navToJob: string;
  addressPlaceholder: string;
  titleLabel: string;
  titlePlaceholder: string;
  detailsPlaceholder: string;
  whenLabel: string;
  urgencyAsap: string;
  urgencyThisWeek: string;
  urgencyPlanning: string;
  budgetHelp: string;
  requestQuotes: string;
  noServices: string;
  clearSearch: string;
  proCTA: string;
  proCTADesc: string;
  proCTABtn: string;
  openCompanyBtn: string;
  popularCategories: string;
  exploreServices: string;
  results: string;
  viewAllServices: string;
  heroTitle: string;
  heroSubtitle: string;
  allServicesTitle: string;
  trustSecure: string;
  trustStars: string;
  trustFast: string;
  connectPortfolio: string;
  connectPortfolioDesc: string;
  connecting: string;
  connectBtn: string;
  autoSync: string;
  instaConnected: string;
  itemsSynced: string;
  disconnect: string;
  noCaption: string;
  postedOn: string;
  wantService: string;
  statusConfirmed: string;
  subConfirmed: string;
  statusEnRoute: string;
  subEnRoute: string;
  statusArrived: string;
  subArrived: string;
  statusInProgress: string;
  subInProgress: string;
  statusCompleted: string;
  subCompleted: string;
  recording: string;
  invoiceNo: string;
  serviceCompleted: string;
  amountHT: string;
  downloadPdf: string;
  proposalUpdate: string;
  offerAccepted: string;
  offerDeclined: string;
  acceptOffer: string;
  typeMessage: string;
  updateOffer: string;
  newPrice: string;
  reasonChange: string;
  sendUpdate: string;
  generateInvoice: string;
  assign: string;
  actionOnWay: string;
  actionArrived: string;
  actionStart: string;
  finishJob: string;
  // Service Workflow
  changeOffer: string;
  executionPending: string;
  executionEnRoute: string;
  executionArrived: string;
  executionInProgress: string;
  executionFinished: string;
  executionPaid: string;
  executionCompleted: string;
  confirmService: string;
  serviceNotDone: string;
  paymentReceived: string;
  paymentPending: string;
  archiveChat: string;
  stepperEnRoute: string;
  stepperArrived: string;
  stepperStart: string;
  stepperFinish: string;
  startCodeLabel: string;
  startCodeEnter: string;
  invalidCode: string;
  teamAssigned: string;
  hireAgain: string;
  // Admin
  adminCatalog: string;
  adminCatalogDesc: string;
  adminAddProduct: string;
  adminProduct: string;
  adminCategory: string;
  adminPrice: string;
  adminStock: string;
  adminType: string;
  adminActions: string;
  adminInternal: string;
  adminPartner: string;
  adminEditProduct: string;
  adminAddNewProduct: string;
  adminFulfillment: string;
  adminMonetization: string;
  adminMonetizationDesc: string;
  adminPaidBoosts: string;
  adminCommRate: string;
  adminCommRateDesc: string;
  adminBilling: string;
  adminMonthly: string;
  loading: string;
  saving: string;
  storeOfficial: string;
  storeHeroTitle: string;
  storeHeroDesc: string;
  storeSearchPlaceholder: string;
  storeAllProducts: string;
  storeInStock: string;
  storeOutOfStock: string;
  storeOfficialBadge: string;
  storePartnerBadge: string;
  boostHeroTitle: string;
  boostHeroDesc: string;
  boostStatusActive: string;
  boostStatusExpires: string;
  boostBestValue: string;
  boostSelectPlan: string;
  boostSelected: string;
  boostActivateNow: string;
  boostDisclaimer: string;
  boostStatusExpiresLong: string;
  days: string;
  processing: string;
  monetizationEngine: string;
  monetizationDesc: string;
  saveAllChanges: string;
  platformDefaults: string;
  defaultCommission: string;
  commissionNote: string;
  paidBoosts: string;
  boostDuration: string;
  subTiers: string;
  monthlyPrice: string;
  featureList: string;
  onePerLine: string;
  noSubPlans: string;
  initDefaultPlans: string;
  ghostMode: string;
  commandCenter: string;
  loggedAsAdmin: string;
  overviewTab: string;
  storeTab: string;
  pricingTab: string;
  livePulse: string;
  totalUsers: string;
  activeJobsTab: string;
  volumeGmv: string;
  topRegion: string;
  trustSafety: string;
  pendingVerifications: string;
  allClear: string;
  proApplicant: string;
  businessReg: string;
  reject: string;
  approveVerify: string;
  regionalDist: string;
  dangerZone: string;
  emergencyBroadcast: string;
  wipeDatabase: string;
  systemLogs: string;
}

const translations: Record<Language, Translations> = {
  en: {
    welcome: "Welcome to Zolver",
    findPro: "Find a Pro",
    searchPlaceholder: "What service do you need?",
    login: "Log In",
    logout: "Log Out",
    signup: "Sign Up",
    profile: "Profile",
    messages: "Messages",
    notifications: "Notifications",
    settings: "Settings",
    OPEN: "Open",
    IN_PROGRESS: "In Progress",
    COMPLETED: "Completed",
    CANCELLED: "Cancelled",
    liveMarket: "Live Market",
    myRequests: "My Requests",
    historyTab: "History",
    teamTab: "Team",
    postJob: "Post a Job",
    viewDetails: "View Details",
    accept: "Accept",
    decline: "Decline",
    hire: "Hire",
    total: 'Total',
    cleaning: "Cleaning",
    moving: "Moving",
    plumbing: "Plumbing",
    electrical: "Electrical",
    painting: "Painting",
    gardening: "Gardening",
    opportunities: "New Opportunities",
    scanningJobs: "Scanning for jobs nearby...",
    financialErp: "Financial & ERP",
    financialPerformance: "Track your business performance",
    addTransaction: "Add Transaction",
    exportReport: "Export Report",
    breakdown: "Breakdown",
    noJobsPeriod: "No transactions for this period",
    manageTeam: "Manage Team",
    manageTeamDesc: "Add and manage your technicians",
    addMember: "Add Member",
    staffAdded: "Staff member added successfully",
    saveEmployee: "Save Employee",
    roleTitle: "Role & Permissions",
    active: "Active",
    inactive: "Inactive",
    fullName: "Full Name",
    emailLogin: "Email (Login)",
    invBillTo: "Bill To",
    invDate: "Date",
    invDue: "Due Date",
    invDesc: "Description",
    invQty: "Qty",
    invRate: "Rate",
    invTotal: "Total",
    invSubtotal: "Subtotal",
    invVatAmt: "VAT Amount",
    invTotalDue: "Total Due",
    invFooter: "Thank you for your business!",
    detailsLabel: "Details",
    photosOptional: "Photos",
    yourOffer: "Your Offer",
    cancel: "Cancel",
    saveChanges: "Save Changes",
    today: "Today",
    yesterday: "Yesterday",
    noHistory: "No history available",
    confirmDelete: "Confirm Delete",
    noActiveRequests: "No active requests found.",
    signIn: "Sign In",
    welcomeSubtitle: "Connecting local talent with people who need things done.",
    loginWithEmail: "Login with Email",
    loginWithPhone: "Login with Phone",
    email: "Email",
    phoneLabel: "Phone Number",
    password: "Password",
    forgotPassword: "Forgot password?",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    createAccount: "Create Account",
    loggedAs: "Logged in as",
    dashboard: "Dashboard",
    whatNeed: "What do you need today?",
    messagesTab: "Messages",
    manageRequests: "Manage Requests",
    createFirstRequest: "Create your first request",
    editRequest: "Edit Request",
    deleteRequest: "Delete Request",
    goToMarket: "Go to Market",
    waitingClient: "Waiting for client",
    acceptAndChat: "Accept & Chat",
    noRequestsDesc: "You don't have any requests yet. Start by posting one!",
    favoritesTab: "Favorites",
    noFavorites: "No favorites yet",
    instaPortfolio: "Instagram Portfolio",
    clientRole: "Client",
    reliableClient: "Reliable Client",
    requestsMade: "Requests Made",
    paymentRate: "Payment Rate",
    speaks: "Speaks",
    serviceLocation: "Service Location",
    openMaps: "Open in Maps",
    verifiedBadge: "Verified Professional",
    jobs: "Jobs",
    onlinePresence: "Online Presence",
    businessHours: "Business Hours",
    bio: "Bio",
    serviceTimeline: "Service Timeline",
    contactInfo: "Contact Info",
    removeFromFavorites: "Remove from Favorites",
    addToFavorites: "Add to Favorites",
    unblockContact: "Unblock Contact",
    blockContact: "Block Contact",
    hireNow: "Hire Now",
    imClient: "I'm a Client",
    imPro: "I'm a Professional",
    back: "Back",
    noCompany: "I don't have a company yet",
    personalDetails: "Personal Details",
    businessDetails: "Business Details",
    servicesAndScope: "Services & Scope",
    licenseDetails: "License Details",
    financialPlan: "Financial Plan",
    reviewDetails: "Review & Confirm",
    stepIndicator: "Step {step} of {total}",
    confirmPasswordLabel: "Confirm Password",
    cnsNumber: "CNS Number",
    street: "Street",
    number: "Number",
    floor: "Floor / Apt",
    residence: "Residence",
    elevator: "Elevator",
    parking: "Parking",
    addAddress: "Add Address",
    postalCode: "Postal Code",
    locality: "Locality",
    idUpload: "ID Card / Passport",
    attached: "File attached",
    independant: "Independent / Freelance",
    societe: "Company (S.à r.l, S.A, etc.)",
    companyName: "Company Name",
    tvaNumber: "VAT Number",
    rcsNumber: "RCS Number",
    selectServices: "Select your services",
    selectServicesDesc: "Choose the services you offer to clients",
    licenseInfo: "Business License Information",
    licenseNum: "License Number",
    licenseExpiry: "Expiry Date",
    uploadPdfLabel: "Upload License (PDF/Image)",
    licenseUploaded: "License uploaded successfully",
    planSelect: "Select your plan",
    founderOffer: "Early Founder Offer",
    premiumPlan: "Premium Professional",
    lifetimeAccess: "Lifetime Access",
    benefitSite: "Custom Professional Website",
    benefitPriority: "Priority in search results",
    benefitFees: "0% Service Fees",
    benefitSupport: "24/7 Dedicated Support",
    benefitBadge: "Founder Member Badge",
    durationLabel: "/ month",
    freeForever: "Free Forever",
    basicPlan: "Basic",
    basicDesc: "Perfect to get started",
    payoutDetails: "Payout Details",
    iban: "IBAN",
    accHolder: "Account Holder Name",
    paymentMethod: "Subscription Payment Method",
    paymentValidation: "Verify & Secure",
    expiryDate: "MM/YY",
    cvc: "CVC",
    cardHolder: "Cardholder Name",
    websiteReady: "Your website is ready!",
    websiteDesc: "We've generated a professional landing page for your business.",
    visitSite: "Visit my website",
    generatedFor: "Generated for",
    summaryServices: "Selected Services",
    summaryPlan: "Chosen Plan",
    summaryIban: "Payout IBAN",
    declaration: "I declare that all information is true",
    finish: "Finish Setup",
    next: "Next",
    welcomeBack: "Welcome back!",
    personalInfo: "Personal Information",
    manageIdentity: "Manage your identity and contact info",
    languages: "Languages",
    addressLogistics: "Address & Logistics",
    smartAddress: "Smart Address Finder",
    houseNumber: "House Number",
    security: "Security",
    blockedUsers: "Blocked Users",
    noBlockedUsers: "No blocked users",
    smartReply: "AI Smart Reply",
    smartReplyDesc: "Automate your first responses to clients",
    enableAutoReply: "Enable Auto-Reply",
    activationTime: "Activation Time",
    immediate: "Immediate",
    mins5: "after 5 mins",
    mins15: "after 15 mins",
    botPersonality: "Bot Personality",
    agilityMode: "Agility",
    agilityDesc: "Fast, concise and helpful",
    dataMode: "Data-Driven",
    dataDesc: "Focuses on gathering job details",
    customMode: "Custom",
    customDesc: "Write your own greeting",
    yourMessage: "Your Message",
    botMessageCustomDefault: "Hello! Thank you for your request. How can I help you today?",
    preview: "Preview",
    botMessageAgility: "Hi! I'm the Zolver AI. I'm here to help you get started while the pro is busy.",
    botMessageData: "Hello! To provide a better quote, could you please tell me more about the project?",
    botMsgFooter: "Zolver AI Assistant",
    siteStatus: "Website Status",
    online: "Online",
    offline: "Offline",
    shareWhatsapp: "Share on WhatsApp",
    appearance: "Appearance",
    selectTheme: "Select Theme",
    accentColor: "Accent Color",
    previewSite: "Preview Site",
    siteInfo: "Site Content",
    siteInfoDesc: "Update your business description and hours",
    visitExternal: "Visit external site",
    companyDesc: "Business Description",
    cantEditHelp: "Contact support to change this",
    workingDays: "Working Days",
    openingTime: "Opening Time",
    closingTime: "Closing Time",
    subscription: "Subscription",
    currentPlan: "Current Plan",
    activePlan: "Active Plan",
    upgradeBtn: "Upgrade to Premium",
    paymentCard: "Payment Card",
    legalForm: "Legal Form",
    banking: "Banking",
    logisticsNote: "Logistics Note",
    luxNoteDesc: "Luxembourg specific logistics",
    clientRoleDesc: "I want to hire professionals",
    reliableClientDesc: "Trusted community member",
    myWebsite: "My Website",
    chatSettings: "Chat Settings",
    themeModern: "Modern",
    themeClassic: "Classic",
    themeBold: "Bold",
    themeMinimal: "Minimal",
    companyData: "Company Data",
    companyLocation: "Company Location",
    staffRestriction: "Staff Restricted",
    staffRestrictionDesc: "You don't have access to this feature. Please contact your manager.",
    staffDashboard: "Staff Dashboard",
    navToJob: "Navigate to Job",
    addressPlaceholder: "Enter service address...",
    titleLabel: "Request Title",
    titlePlaceholder: "e.g., Living room painting",
    detailsPlaceholder: "Describe what needs to be done...",
    whenLabel: "When?",
    urgencyAsap: "ASAP",
    urgencyThisWeek: "This Week",
    urgencyPlanning: "Planning ahead",
    budgetHelp: "The pro will confirm the final price after review.",
    requestQuotes: "Request Quotes",
    noServices: "No services found for",
    clearSearch: "Clear Search",
    proCTA: "Are you a Professional?",
    proCTADesc: "Join Zolver and grow your business today.",
    proCTABtn: "Get Started as a Pro",
    openCompanyBtn: "Open Zolver for Business",
    popularCategories: "Popular Categories",
    exploreServices: "Find the best professionals in Luxembourg",
    results: "results",
    viewAllServices: "View All Services",
    heroTitle: "Find the best <span class='text-orange-500'>Pro</span> for any task",
    heroSubtitle: "Book verified professionals for cleaning, repairs, beauty, and more.",
    allServicesTitle: "All Services",
    trustSecure: "Secure Payments",
    trustStars: "Verified Reviews",
    trustFast: "Instant Booking",
    connectPortfolio: "Connect your Portfolio",
    connectPortfolioDesc: "Showcase your work directly from Instagram on your profile.",
    connecting: "Connecting...",
    connectBtn: "Connect Instagram",
    autoSync: "Automatic sync enabled",
    instaConnected: "Instagram Connected",
    itemsSynced: "items synced",
    disconnect: "Disconnect",
    noCaption: "No caption provided.",
    postedOn: "Posted on",
    wantService: "I want this service",
    statusConfirmed: "Booking Confirmed",
    subConfirmed: "The professional will arrive at the scheduled time.",
    statusEnRoute: "Pro is on the way",
    subEnRoute: "Coming to your location now.",
    statusArrived: "Pro has arrived",
    subArrived: "The professional is at the location.",
    statusInProgress: "Service in Progress",
    subInProgress: "The task is being performed.",
    statusCompleted: "Service Completed",
    subCompleted: "The task has been finished. Thank you!",
    recording: "Recording",
    invoiceNo: "Invoice",
    serviceCompleted: "Service Completed",
    amountHT: "Amount (Excl. VAT)",
    downloadPdf: "Download PDF",
    proposalUpdate: "Proposal Update",
    offerAccepted: "Offer Accepted",
    offerDeclined: "Offer Declined",
    acceptOffer: "Accept Offer",
    typeMessage: "Type a message...",
    updateOffer: "Update Offer",
    newPrice: "New Price",
    reasonChange: "Reason for change",
    sendUpdate: "Send Update",
    generateInvoice: "Generate Invoice",
    assign: "Assign Team",
    actionOnWay: "I'm on my way",
    actionArrived: "I've arrived",
    actionStart: "Start Work",
    finishJob: "Mark as Finished",
    // Workflow
    changeOffer: "Change Details/Offer",
    executionPending: "Pending",
    executionEnRoute: "En Route",
    executionArrived: "Arrived",
    executionInProgress: "In Progress",
    executionFinished: "Finished",
    executionPaid: "Paid",
    executionCompleted: "Completed",
    confirmService: "Confirm Service Completed?",
    serviceNotDone: "Not Done Yet",
    paymentReceived: "Payment Received?",
    paymentPending: "Pending Payment",
    archiveChat: "Archive Ticket",
    stepperEnRoute: "Depart",
    stepperArrived: "Arrive",
    stepperStart: "Start",
    stepperFinish: "Finish",
    startCodeLabel: "Security Start Code",
    startCodeEnter: "Enter 4-digit code to start",
    invalidCode: "Invalid Code",
    teamAssigned: "Team member assigned to this request",
    hireAgain: "Hire Again",
    // Admin
    adminCatalog: "Catalog Management",
    adminCatalogDesc: "Add products and manage fulfillment logic.",
    adminAddProduct: "Add Product",
    adminProduct: "Product",
    adminCategory: "Category",
    adminPrice: "Price",
    adminStock: "Stock",
    adminType: "Type",
    adminActions: "Actions",
    adminInternal: "Internal",
    adminPartner: "Partner",
    adminEditProduct: "Edit Product",
    adminAddNewProduct: "Add New Product",
    adminFulfillment: "Fulfillment",
    monetizationEngine: "Monetization Engine",
    monetizationDesc: "Control fees, plans, and marketing costs globally.",
    saveAllChanges: "Save All Changes",
    platformDefaults: "Platform Defaults",
    defaultCommission: "Default Commission Rate (%)",
    commissionNote: "Applied to all jobs if no specific plan overrides it.",
    paidBoosts: "Paid Boosts (Marketing)",
    boostDuration: "Duration (Days)",
    subTiers: "Professional Subscription Tiers",
    monthlyPrice: "Monthly Price",
    featureList: "Features (JSON or List)",
    onePerLine: "One feature per line",
    noSubPlans: "No subscription plans defined.",
    initDefaultPlans: "Initialize Default Plans",
    ghostMode: "Ghost Mode",
    commandCenter: "COMMAND",
    loggedAsAdmin: "LOGGED AS",
    overviewTab: "Overview",
    storeTab: "Store Manager",
    pricingTab: "Pricing Config",
    livePulse: "Live Pulse",
    totalUsers: "Total Users",
    activeJobsTab: "Active Jobs",
    volumeGmv: "Volume (GMV)",
    topRegion: "Top Region",
    trustSafety: "Trust & Safety",
    pendingVerifications: "Pending Verifications",
    allClear: "All clear. No pending verifications.",
    proApplicant: "PRO APPLICANT",
    businessReg: "Business Reg",
    reject: "REJECT",
    approveVerify: "APPROVE & VERIFY",
    regionalDist: "Regional Distribution",
    dangerZone: "Danger Zone",
    emergencyBroadcast: "EMERGENCY BROADCAST",
    wipeDatabase: "WIPE DATABASE",
    systemLogs: "SYSTEM_LOGS",
    adminMonetization: "Monetization Engine",
    adminMonetizationDesc: "Control fees, plans, and marketing costs globally.",
    adminPaidBoosts: "Paid Boosts (Marketing)",
    adminCommRate: "Commission Rate (%)",
    adminCommRateDesc: "Applied to all jobs if no specific plan overrides it.",
    adminBilling: "Billing",
    adminMonthly: "Monthly",
    loading: "Loading",
    saving: "Saving",
    storeOfficial: "Official Zolver Store",
    storeHeroTitle: "Gear Up Like a Pro",
    storeHeroDesc: "Get official merchandise, high-quality uniforms, and professional grade tools delivered directly to your job site.",
    storeSearchPlaceholder: "Search gear...",
    storeAllProducts: "All Products",
    storeInStock: "in stock",
    storeOutOfStock: "Out of Stock",
    storeOfficialBadge: "OFFICIAL",
    storePartnerBadge: "PARTNER",
    boostHeroTitle: "Boost Your Profile",
    boostHeroDesc: "Get up to 5x more job leads by featuring your profile.",
    boostStatusActive: "Boost Active!",
    boostStatusExpires: "Your profile is boosted until",
    boostBestValue: "BEST VALUE",
    boostSelectPlan: "Select Plan",
    boostSelected: "Selected",
    boostActivateNow: "Activate Boost Now",
    boostDisclaimer: "By activating a boost, you agree to our marketing terms. The boost is applied immediately and is non-refundable.",
    boostStatusExpiresLong: "You are now boosted for",
    days: "days",
    processing: "Processing..."
  },
  fr: {
    welcome: "Bienvenue sur Zolver",
    findPro: "Trouver un Pro",
    searchPlaceholder: "De quel service avez-vous besoin ?",
    login: "Connexion",
    logout: "Déconnexion",
    signup: "S'inscrire",
    profile: "Profil",
    messages: "Messages",
    notifications: "Notifications",
    settings: "Paramètres",
    OPEN: "Ouvert",
    IN_PROGRESS: "En Cours",
    COMPLETED: "Terminé",
    CANCELLED: "Annulé",
    liveMarket: "Marché en Direct",
    myRequests: "Mes Demandes",
    historyTab: "Historique",
    teamTab: "Équipe",
    postJob: "Publier une mission",
    viewDetails: "Voir Détails",
    accept: "Accepter",
    decline: "Refuser",
    hire: "Engager",
    total: 'Total',
    cleaning: "Nettoyage",
    moving: "Déménagement",
    plumbing: "Plomberie",
    electrical: "Électricité",
    painting: "Peinture",
    gardening: "Jardinage",
    opportunities: "Nouvelles Opportunités",
    scanningJobs: "Recherche de missions à proximité...",
    financialErp: "Finance & ERP",
    financialPerformance: "Suivez la performance de votre entreprise",
    addTransaction: "Ajouter Transaction",
    exportReport: "Exporter Rapport",
    breakdown: "Détail",
    noJobsPeriod: "Aucune transaction pour cette période",
    manageTeam: "Gérer l'équipe",
    manageTeamDesc: "Ajoutez et gérez vos techniciens",
    addMember: "Ajouter Membre",
    staffAdded: "Membre ajouté avec succès",
    saveEmployee: "Enregistrer Employé",
    roleTitle: "Rôle et Permissions",
    active: "Actif",
    inactive: "Inactif",
    fullName: "Nom Complet",
    emailLogin: "Email (Connexion)",
    invBillTo: "Facturer à",
    invDate: "Date",
    invDue: "Échéance",
    invDesc: "Description",
    invQty: "Qté",
    invRate: "Prix Unitaire",
    invTotal: "Total",
    invSubtotal: "Sous-total",
    invVatAmt: "Montant TVA",
    invTotalDue: "Total à Payer",
    invFooter: "Merci de votre confiance !",
    detailsLabel: "Détails",
    photosOptional: "Photos",
    yourOffer: "Votre Offre",
    cancel: "Annuler",
    saveChanges: "Enregistrer",
    today: "Aujourd'hui",
    yesterday: "Hier",
    noHistory: "Aucun historique disponible",
    confirmDelete: "Confirmer la suppression",
    noActiveRequests: "Aucune demande active trouvée.",
    signIn: "Se connecter",
    welcomeSubtitle: "Connecter les talents locaux avec ceux qui en ont besoin.",
    loginWithEmail: "Connexion par Email",
    loginWithPhone: "Connexion par Téléphone",
    email: "Email",
    phoneLabel: "Numéro de Téléphone",
    password: "Mot de Passe",
    forgotPassword: "Mot de passe oublié ?",
    dontHaveAccount: "Vous n'avez pas de compte ?",
    signUp: "S'inscrire",
    createAccount: "Créer un compte",
    loggedAs: "Connecté en tant que",
    dashboard: "Tableau de Bord",
    whatNeed: "De quoi avez-vous besoin aujourd'hui ?",
    messagesTab: "Messages",
    manageRequests: "Gérer mes demandes",
    createFirstRequest: "Créer votre première demande",
    editRequest: "Modifier la demande",
    deleteRequest: "Supprimer la demande",
    goToMarket: "Aller au Marché",
    waitingClient: "En attente du client",
    acceptAndChat: "Accepter & Chatter",
    noRequestsDesc: "Vous n'avez pas encore de demande. Commencez par en publier une !",
    favoritesTab: "Favoris",
    noFavorites: "Pas encore de favoris",
    instaPortfolio: "Portfolio Instagram",
    clientRole: "Client",
    reliableClient: "Client Fiable",
    requestsMade: "Demandes Faites",
    paymentRate: "Taux de Paiement",
    speaks: "Parle",
    serviceLocation: "Lieu du Service",
    openMaps: "Ouvrir dans Maps",
    verifiedBadge: "Professionnel Vérifié",
    jobs: "Missions",
    onlinePresence: "Présence en Ligne",
    businessHours: "Heures d'Ouverture",
    bio: "Bio",
    serviceTimeline: "Historique des Services",
    contactInfo: "Infos de Contact",
    removeFromFavorites: "Retirer des Favoris",
    addToFavorites: "Ajouter aux Favoris",
    unblockContact: "Débloquer le Contact",
    blockContact: "Bloquer le Contact",
    hireNow: "Engager Maintenant",
    imClient: "Je suis un Client",
    imPro: "Je suis un Professionnel",
    back: "Retour",
    noCompany: "Je n'ai pas encore d'entreprise",
    personalDetails: "Détails Personnels",
    businessDetails: "Détails de l'Entreprise",
    servicesAndScope: "Services et Portée",
    licenseDetails: "Détails de la Licence",
    financialPlan: "Plan Financier",
    reviewDetails: "Réviser et Confirmer",
    stepIndicator: "Étape {step} sur {total}",
    confirmPasswordLabel: "Confirmer le Mot de Passe",
    cnsNumber: "Numéro de CNS",
    street: "Rue",
    number: "Numéro",
    floor: "Étage / Apt",
    residence: "Résidence",
    elevator: "Ascenseur",
    parking: "Parking",
    addAddress: "Ajouter une adresse",
    postalCode: "Code Postal",
    locality: "Localité",
    idUpload: "Carte d'Identité / Passeport",
    attached: "Fichier joint",
    independant: "Indépendant / Freelance",
    societe: "Société (S.à r.l, S.A, etc.)",
    companyName: "Nom de l'Entreprise",
    tvaNumber: "Numéro de TVA",
    rcsNumber: "Numéro de RCS",
    selectServices: "Sélectionnez vos services",
    selectServicesDesc: "Choisissez les services que vous offrez aux clients",
    licenseInfo: "Informations sur la Licence Commerciale",
    licenseNum: "Numéro de Licence",
    licenseExpiry: "Date d'Expiration",
    uploadPdfLabel: "Télécharger la Licence (PDF/Image)",
    licenseUploaded: "Licence téléchargée avec succès",
    planSelect: "Sélectionnez votre plan",
    founderOffer: "Offre Fondateur",
    premiumPlan: "Professionnel Premium",
    lifetimeAccess: "Accès à Vie",
    benefitSite: "Site Web Professionnel Personnalisé",
    benefitPriority: "Priorité dans les résultats de recherche",
    benefitFees: "0% de Frais de Service",
    benefitSupport: "Support Dédié 24/7",
    benefitBadge: "Badge Membre Fondateur",
    durationLabel: "/ mois",
    freeForever: "Gratuit pour toujours",
    basicPlan: "Basique",
    basicDesc: "Parfait pour commencer",
    payoutDetails: "Détails de Paiement",
    iban: "IBAN",
    accHolder: "Nom du Titulaire du Compte",
    paymentMethod: "Mode de Paiement de l'Abonnement",
    paymentValidation: "Vérifier et Sécuriser",
    expiryDate: "MM/AA",
    cvc: "CVC",
    cardHolder: "Nom du Titulaire de la Carte",
    websiteReady: "Votre site est prêt !",
    websiteDesc: "Nous avons généré une page de destination professionnelle pour votre entreprise.",
    visitSite: "Visiter mon site web",
    generatedFor: "Généré pour",
    summaryServices: "Services Sélectionnés",
    summaryPlan: "Plan Choisi",
    summaryIban: "IBAN de Paiement",
    declaration: "Je déclare que toutes les informations sont exactes",
    finish: "Terminer la configuration",
    next: "Suivant",
    welcomeBack: "Bon retour !",
    personalInfo: "Informations Personnelles",
    manageIdentity: "Gérez votre identité et vos coordonnées",
    languages: "Langues",
    addressLogistics: "Adresse et Logistique",
    smartAddress: "Recherche d'Adresse Intelligente",
    houseNumber: "Numéro de Maison",
    security: "Sécurité",
    blockedUsers: "Utilisateurs Bloqués",
    noBlockedUsers: "Aucun utilisateur bloqué",
    smartReply: "Réponse Intelligente IA",
    smartReplyDesc: "Automatisez vos premières réponses aux clients",
    enableAutoReply: "Activer l'Auto-Réponse",
    activationTime: "Délai d'Activation",
    immediate: "Immédiat",
    mins5: "après 5 mins",
    mins15: "après 15 mins",
    botPersonality: "Personnalité du Bot",
    agilityMode: "Agilité",
    agilityDesc: "Rapide, concis et utile",
    dataMode: "Axé sur les données",
    dataDesc: "Se concentre sur la collecte des détails de la mission",
    customMode: "Personnalisé",
    customDesc: "Rédigez votre propre message d'accueil",
    yourMessage: "Votre Message",
    botMessageCustomDefault: "Bonjour ! Merci pour votre demande. Comment puis-je vous aider aujourd'hui ?",
    preview: "Aperçu",
    botMessageAgility: "Bonjour ! Je suis l'IA de Zolver. Je suis là pour vous aider à démarrer pendant que le pro est occupé.",
    botMessageData: "Bonjour ! Pour fournir un meilleur devis, pourriez-vous m'en dire plus sur le projet ?",
    botMsgFooter: "Assistant IA Zolver",
    siteStatus: "Statut du Site Web",
    online: "En Ligne",
    offline: "Hors Ligne",
    shareWhatsapp: "Partager sur WhatsApp",
    appearance: "Apparence",
    selectTheme: "Sélectionner le Thème",
    accentColor: "Couleur d'Accent",
    previewSite: "Aperçu du Site",
    siteInfo: "Contenu du Site",
    siteInfoDesc: "Mettez à jour la description et les horaires de votre entreprise",
    visitExternal: "Visiter le site externe",
    companyDesc: "Description de l'Entreprise",
    cantEditHelp: "Contactez le support pour modifier ceci",
    workingDays: "Jours de Travail",
    openingTime: "Heure d'Ouverture",
    closingTime: "Heure de Fermeture",
    subscription: "Abonnement",
    currentPlan: "Plan Actuel",
    activePlan: "Plan Actif",
    upgradeBtn: "Passer au Premium",
    paymentCard: "Carte de Paiement",
    legalForm: "Forme Juridique",
    banking: "Banque",
    logisticsNote: "Note Logistique",
    luxNoteDesc: "Logistique spécifique au Luxembourg",
    clientRoleDesc: "Je souhaite engager des professionnels",
    reliableClientDesc: "Membre de confiance de la communauté",
    myWebsite: "Mon Site Web",
    chatSettings: "Paramètres de Chat",
    themeModern: "Moderne",
    themeClassic: "Classique",
    themeBold: "Audacieux",
    themeMinimal: "Minimal",
    companyData: "Données de l'Entreprise",
    companyLocation: "Localisation de l'Entreprise",
    staffRestriction: "Accès Restreint",
    staffRestrictionDesc: "Vous n'avez pas accès à cette fonctionnalité. Veuillez contacter votre responsable.",
    staffDashboard: "Tableau de Bord Personnel",
    navToJob: "Naviguer vers la mission",
    addressPlaceholder: "Saisissez l'adresse du service...",
    titleLabel: "Titre de la demande",
    titlePlaceholder: "ex: Peinture salon",
    detailsPlaceholder: "Décrivez ce qu'il y a à faire...",
    whenLabel: "Quand ?",
    urgencyAsap: "Dès que possible",
    urgencyThisWeek: "Cette semaine",
    urgencyPlanning: "En planification",
    budgetHelp: "Le pro confirmera le prix final après examen.",
    requestQuotes: "Demander des devis",
    noServices: "Aucun service trouvé pour",
    clearSearch: "Effacer la recherche",
    proCTA: "Vous êtes un professionnel ?",
    proCTADesc: "Rejoignez Zolver et développez votre activité dès aujourd'hui.",
    proCTABtn: "Commencer en tant que Pro",
    openCompanyBtn: "Ouvrir Zolver for Business",
    popularCategories: "Catégories Populaires",
    exploreServices: "Trouvez les meilleurs professionnels au Luxembourg",
    results: "résultats",
    viewAllServices: "Voir tous les services",
    heroTitle: "Trouvez le meilleur <span class='text-orange-500'>Pro</span> pour chaque tâche",
    heroSubtitle: "Réservez des professionnels vérifiés pour le nettoyage, les réparations, la beauté et plus.",
    allServicesTitle: "Tous les Services",
    trustSecure: "Paiements sécurisés",
    trustStars: "Avis vérifiés",
    trustFast: "Réservation instantanée",
    connectPortfolio: "Connectez votre Portfolio",
    connectPortfolioDesc: "Affichez votre travail directement depuis Instagram sur votre profil.",
    connecting: "Connexion...",
    connectBtn: "Connecter Instagram",
    autoSync: "Synchronisation automatique activée",
    instaConnected: "Instagram connecté",
    itemsSynced: "articles synchronisés",
    disconnect: "Déconnecter",
    noCaption: "Aucune légende fournie.",
    postedOn: "Publié le",
    wantService: "Je veux ce service",
    statusConfirmed: "Réservation confirmée",
    subConfirmed: "Le professionnel arrivera à l'heure prévue.",
    statusEnRoute: "Le Pro est en route",
    subEnRoute: "Arrive à votre emplacement maintenant.",
    statusArrived: "Le Pro est arrivé",
    subArrived: "Le professionnel est sur place.",
    statusInProgress: "Service en cours",
    subInProgress: "La tâche est en cours d'exécution.",
    statusCompleted: "Service terminé",
    subCompleted: "La tâche a été terminée. Merci !",
    recording: "Enregistrement",
    invoiceNo: "Facture",
    serviceCompleted: "Service terminé",
    amountHT: "Montant HT",
    downloadPdf: "Télécharger le PDF",
    proposalUpdate: "Mise à jour de la proposition",
    offerAccepted: "Offre acceptée",
    offerDeclined: "Offre déclinée",
    acceptOffer: "Accepter l'offre",
    typeMessage: "Tapez un message...",
    updateOffer: "Mettre à jour l'offre",
    newPrice: "Nouveau prix",
    reasonChange: "Raison du changement",
    sendUpdate: "Envoyer la mise à jour",
    generateInvoice: "Générer la facture",
    assign: "Assigner l'équipe",
    actionOnWay: "Je suis en route",
    actionArrived: "Je suis arrivé",
    actionStart: "Démarrer le travail",
    finishJob: "Marquer comme terminé",
    // Workflow - FR
    changeOffer: "Modifier l'Offre",
    executionPending: "En Attente",
    executionEnRoute: "En Route",
    executionArrived: "Arrivé",
    executionInProgress: "En Cours",
    executionFinished: "Terminé",
    executionPaid: "Payé",
    executionCompleted: "Clôturé",
    confirmService: "Confirmer la fin du service ?",
    serviceNotDone: "Pas encore fait",
    paymentReceived: "Paiement Reçu ?",
    paymentPending: "Paiement en attente",
    archiveChat: "Archiver le Ticket",
    stepperEnRoute: "Départ",
    stepperArrived: "Arrivée",
    stepperStart: "Début",
    stepperFinish: "Fin",
    startCodeLabel: "Code de Sécurité",
    startCodeEnter: "Entrez le code à 4 chiffres",
    invalidCode: "Code Invalide",
    teamAssigned: "Membre de l'équipe assigné",
    hireAgain: "Engager à Nouveau",
    // Admin
    adminCatalog: "Catalog Management",
    adminCatalogDesc: "Add products and manage fulfillment logic.",
    adminAddProduct: "Add Product",
    adminProduct: "Product",
    adminCategory: "Category",
    adminPrice: "Price",
    adminStock: "Stock",
    adminType: "Type",
    adminActions: "Actions",
    adminInternal: "Internal",
    adminPartner: "Partner",
    adminEditProduct: "Edit Product",
    adminAddNewProduct: "Add New Product",
    adminFulfillment: "Fulfillment",
    monetizationEngine: "Monetization Engine",
    monetizationDesc: "Control fees, plans, and marketing costs globally.",
    saveAllChanges: "Save All Changes",
    platformDefaults: "Platform Defaults",
    defaultCommission: "Default Commission Rate (%)",
    commissionNote: "Applied to all jobs if no specific plan overrides it.",
    paidBoosts: "Paid Boosts (Marketing)",
    boostDuration: "Duration (Days)",
    subTiers: "Professional Subscription Tiers",
    monthlyPrice: "Monthly Price",
    featureList: "Features (JSON or List)",
    onePerLine: "One feature per line",
    noSubPlans: "No subscription plans defined.",
    initDefaultPlans: "Initialize Default Plans",
    ghostMode: "Ghost Mode",
    commandCenter: "COMMAND",
    loggedAsAdmin: "LOGGED AS",
    overviewTab: "Overview",
    storeTab: "Store Manager",
    pricingTab: "Pricing Config",
    livePulse: "Live Pulse",
    totalUsers: "Total Users",
    activeJobsTab: "Active Jobs",
    volumeGmv: "Volume (GMV)",
    topRegion: "Top Region",
    trustSafety: "Trust & Safety",
    pendingVerifications: "Pending Verifications",
    allClear: "All clear. No pending verifications.",
    proApplicant: "PRO APPLICANT",
    businessReg: "Business Reg",
    reject: "REJECT",
    approveVerify: "APPROVE & VERIFY",
    regionalDist: "Regional Distribution",
    dangerZone: "Danger Zone",
    emergencyBroadcast: "EMERGENCY BROADCAST",
    wipeDatabase: "WIPE DATABASE",
    systemLogs: "SYSTEM_LOGS",
    adminMonetization: "Monetization Engine",
    adminMonetizationDesc: "Control fees, plans, and marketing costs globally.",
    adminPaidBoosts: "Paid Boosts (Marketing)",
    adminCommRate: "Commission Rate (%)",
    adminCommRateDesc: "Applied to all jobs if no specific plan overrides it.",
    adminBilling: "Billing",
    adminMonthly: "Monthly",
    loading: "Loading",
    saving: "Saving",
    storeOfficial: "Official Zolver Store",
    storeHeroTitle: "Gear Up Like a Pro",
    storeHeroDesc: "Get official merchandise, high-quality uniforms, and professional grade tools delivered directly to your job site.",
    storeSearchPlaceholder: "Search gear...",
    storeAllProducts: "All Products",
    storeInStock: "in stock",
    storeOutOfStock: "Out of Stock",
    storeOfficialBadge: "OFFICIAL",
    storePartnerBadge: "PARTNER",
    boostHeroTitle: "Boost Your Profile",
    boostHeroDesc: "Get up to 5x more job leads by featuring your profile.",
    boostStatusActive: "Boost Active!",
    boostStatusExpires: "Your profile is boosted until",
    boostBestValue: "BEST VALUE",
    boostSelectPlan: "Select Plan",
    boostSelected: "Selected",
    boostActivateNow: "Activate Boost Now",
    boostDisclaimer: "By activating a boost, you agree to our marketing terms. The boost is applied immediately and is non-refundable.",
    boostStatusExpiresLong: "You are now boosted for",
    days: "days",
    processing: "Processing..."
  },
  pt: {
    welcome: "Bem-vindo ao Zolver",
    findPro: "Encontrar Profissional",
    searchPlaceholder: "Que serviço precisa?",
    login: "Entrar",
    logout: "Sair",
    signup: "Registar",
    profile: "Perfil",
    messages: "Mensagens",
    notifications: "Notificações",
    settings: "Definições",
    OPEN: "Aberto",
    IN_PROGRESS: "Em Progresso",
    COMPLETED: "Concluído",
    CANCELLED: "Cancelado",
    liveMarket: "Mercado ao Vivo",
    myRequests: "Meus Pedidos",
    historyTab: "Histórico",
    teamTab: "Equipa",
    postJob: "Publicar Pedido",
    viewDetails: "Ver Detalhes",
    accept: "Aceitar",
    decline: "Recusar",
    hire: "Contratar",
    total: 'Total',
    cleaning: "Limpezas",
    moving: "Mudanças",
    plumbing: "Canalização",
    electrical: "Eletricidade",
    painting: "Pintura",
    gardening: "Jardinagem",
    opportunities: "Novas Oportunidades",
    scanningJobs: "A procurar trabalhos próximos...",
    financialErp: "Finanças e ERP",
    financialPerformance: "Acompanhe o desempenho do seu negócio",
    addTransaction: "Adicionar Transação",
    exportReport: "Exportar Relatório",
    breakdown: "Detalhes",
    noJobsPeriod: "Sem transações neste período",
    manageTeam: "Gerir Equipa",
    manageTeamDesc: "Adicione e gerencie seus técnicos",
    addMember: "Adicionar Membro",
    staffAdded: "Funcionário adicionado com sucesso",
    saveEmployee: "Guardar Funcionário",
    roleTitle: "Função e Permissões",
    active: "Ativo",
    inactive: "Inativo",
    fullName: "Nome Completo",
    emailLogin: "Email (Login)",
    invBillTo: "Faturar a",
    invDate: "Data",
    invDue: "Vencimento",
    invDesc: "Descrição",
    invQty: "Qtd",
    invRate: "Preço Unit.",
    invTotal: "Total",
    invSubtotal: "Subtotal",
    invVatAmt: "IVA",
    invTotalDue: "Total a Pagar",
    invFooter: "Obrigado pela preferência!",
    detailsLabel: "Detalhes",
    photosOptional: "Fotos",
    yourOffer: "Sua Oferta",
    cancel: "Cancelar",
    saveChanges: "Guardar Alterações",
    today: "Hoje",
    yesterday: "Ontem",
    noHistory: "Sem histórico disponível",
    confirmDelete: "Confirmar Eliminação",
    noActiveRequests: "Nenhum pedido ativo encontrado.",
    signIn: "Entrar",
    welcomeSubtitle: "Conectando talentos locais com quem precisa de serviços.",
    loginWithEmail: "Entrar com Email",
    loginWithPhone: "Entrar com Telefone",
    email: "Email",
    phoneLabel: "Número de Telefone",
    password: "Palavra-passe",
    forgotPassword: "Esqueceu a palavra-passe?",
    dontHaveAccount: "Não tem uma conta?",
    signUp: "Registar",
    createAccount: "Criar Conta",
    loggedAs: "Logado como",
    dashboard: "Painel de Controlo",
    whatNeed: "Do que precisa hoje?",
    messagesTab: "Mensagens",
    manageRequests: "Gerir Pedidos",
    createFirstRequest: "Crie o seu primeiro pedido",
    editRequest: "Editar Pedido",
    deleteRequest: "Eliminar Pedido",
    goToMarket: "Ir para o Mercado",
    waitingClient: "Aguardando cliente",
    acceptAndChat: "Aceitar e Conversar",
    noRequestsDesc: "Ainda não tem pedidos. Comece por publicar um!",
    favoritesTab: "Favoritos",
    noFavorites: "Ainda sem favoritos",
    instaPortfolio: "Portfólio Instagram",
    clientRole: "Cliente",
    reliableClient: "Cliente Confiável",
    requestsMade: "Pedidos Feitos",
    paymentRate: "Taxa de Pagamento",
    speaks: "Fala",
    serviceLocation: "Local do Serviço",
    openMaps: "Abrir no Maps",
    verifiedBadge: "Profissional Verificado",
    jobs: "Trabalhos",
    onlinePresence: "Presença Online",
    businessHours: "Horário de Funcionamento",
    bio: "Bio",
    serviceTimeline: "Histórico de Serviços",
    contactInfo: "Informações de Contato",
    removeFromFavorites: "Remover dos Favoritos",
    addToFavorites: "Adicionar aos Favoritos",
    unblockContact: "Desbloquear Contato",
    blockContact: "Bloquear Contato",
    hireNow: "Contratar Agora",
    imClient: "Sou um Cliente",
    imPro: "Sou um Profissional",
    back: "Voltar",
    noCompany: "Ainda não tenho empresa",
    personalDetails: "Detalhes Pessoais",
    businessDetails: "Detalhes da Empresa",
    servicesAndScope: "Serviços e Âmbito",
    licenseDetails: "Detalhes da Licença",
    financialPlan: "Plano Financeiro",
    reviewDetails: "Rever e Confirmar",
    stepIndicator: "Passo {step} de {total}",
    confirmPasswordLabel: "Confirmar Palavra-passe",
    cnsNumber: "Número CNS",
    street: "Rua",
    number: "Número",
    floor: "Andar / Apartamento",
    residence: "Residência / Edifício",
    elevator: "Elevador",
    parking: "Estacionamento",
    addAddress: "Adicionar Endereço",
    postalCode: "Código Postal",
    locality: "Localidade",

    idUpload: "Cartão de Cidadão / Passaporte",
    attached: "Ficheiro anexo",
    independant: "Independente / Freelance",
    societe: "Empresa (S.à r.l, S.A, etc.)",
    companyName: "Nome da Empresa",
    tvaNumber: "Número de IVA",
    rcsNumber: "Número de RCS",
    selectServices: "Selecione os seus serviços",
    selectServicesDesc: "Escolha os serviços que oferece aos clientes",
    licenseInfo: "Informações da Licença Comercial",
    licenseNum: "Número da Licença",
    licenseExpiry: "Data de Validade",
    uploadPdfLabel: "Carregar Licença (PDF/Imagem)",
    licenseUploaded: "Licença carregada com sucesso",
    planSelect: "Selecione o seu plano",
    founderOffer: "Oferta Fundador Early Bird",
    premiumPlan: "Profissional Premium",
    lifetimeAccess: "Acesso Vitalício",
    benefitSite: "Website Profissional Personalizado",
    benefitPriority: "Prioridade nos resultados de pesquisa",
    benefitFees: "0% Taxas de Serviço",
    benefitSupport: "Suporte Dedicado 24/7",
    benefitBadge: "Distintivo de Membro Fundador",
    durationLabel: "/ mês",
    freeForever: "Gratuito para sempre",
    basicPlan: "Básico",
    basicDesc: "Perfeito para começar",
    payoutDetails: "Detalhes de Pagamento",
    iban: "IBAN",
    accHolder: "Nome do Titular da Conta",
    paymentMethod: "Método de Pagamento da Subscrição",
    paymentValidation: "Verificar e Segurar",
    expiryDate: "MM/AA",
    cvc: "CVC",
    cardHolder: "Nome do Titular do Cartão",
    websiteReady: "O seu website está pronto!",
    websiteDesc: "Gerámos uma página de apresentação profissional para o seu negócio.",
    visitSite: "Visitar o meu website",
    generatedFor: "Gerado para",
    summaryServices: "Serviços Selecionados",
    summaryPlan: "Plano Escolhido",
    summaryIban: "IBAN de Pagamento",
    declaration: "Declaro que todas as informações são verdadeiras",
    finish: "Terminar Configuração",
    next: "Próximo",
    welcomeBack: "Bem-vindo de volta!",
    personalInfo: "Informação Pessoal",
    manageIdentity: "Gerencie a sua identidade e contactos",
    languages: "Idiomas",
    addressLogistics: "Morada e Logística",
    smartAddress: "Pesquisa de Morada Inteligente",
    houseNumber: "Número da Porta",
    security: "Segurança",
    blockedUsers: "Utilizadores Bloqueados",
    noBlockedUsers: "Nenhum utilizador bloqueado",
    smartReply: "Resposta Inteligente IA",
    smartReplyDesc: "Automatize as suas primeiras respostas aos clientes",
    enableAutoReply: "Ativar Auto-Resposta",
    activationTime: "Tempo de Ativação",
    immediate: "Imediato",
    mins5: "após 5 min",
    mins15: "após 15 min",
    botPersonality: "Personalidade do Bot",
    agilityMode: "Agilidade",
    agilityDesc: "Rápido, conciso e útil",
    dataMode: "Focado em Dados",
    dataDesc: "Foca-se em recolha de detalhes do trabalho",
    customMode: "Personalizado",
    customDesc: "Escreva a sua própria saudação",
    yourMessage: "A Sua Mensagem",
    botMessageCustomDefault: "Olá! Obrigado pelo seu pedido. Como posso ajudar hoje?",
    preview: "Pré-visualização",
    botMessageAgility: "Olá! Sou a IA do Zolver. Estou aqui para ajudar enquanto o profissional está ocupado.",
    botMessageData: "Olá! Para fornecer um melhor orçamento, poderia dizer-me mais sobre o projeto?",
    botMsgFooter: "Assistente IA Zolver",
    siteStatus: "Estado do Website",
    online: "Online",
    offline: "Offline",
    shareWhatsapp: "Partilhar no WhatsApp",
    appearance: "Aparência",
    selectTheme: "Selecionar Tema",
    accentColor: "Cor de Destaque",
    previewSite: "Pré-visualizar Site",
    siteInfo: "Conteúdo do Site",
    siteInfoDesc: "Atualize a descrição e horários do seu negócio",
    visitExternal: "Visitar site externo",
    companyDesc: "Descrição do Negócio",
    cantEditHelp: "Contacte o suporte para alterar isto",
    workingDays: "Dias de Trabalho",
    openingTime: "Hora de Abertura",
    closingTime: "Hora de Fecho",
    subscription: "Subscrição",
    currentPlan: "Plano Atual",
    activePlan: "Plano Ativo",
    upgradeBtn: "Upgrade para Premium",
    paymentCard: "Cartão de Pagamento",
    legalForm: "Forma Legal",
    banking: "Banca",
    logisticsNote: "Nota de Logística",
    luxNoteDesc: "Logística específica do Luxemburgo",
    clientRoleDesc: "Quero contratar profissionais",
    reliableClientDesc: "Membro confiável da comunidade",
    myWebsite: "O Meu Website",
    chatSettings: "Definições de Chat",
    themeModern: "Moderno",
    themeClassic: "Clássico",
    themeBold: "Audaz",
    themeMinimal: "Minimalista",
    companyData: "Dados da Empresa",
    companyLocation: "Localização da Empresa",
    staffRestriction: "Acesso Restrito",
    staffRestrictionDesc: "Você não tem acesso a esta funcionalidade. Por favor, contacte o seu gerente.",
    staffDashboard: "Painel de Staff",
    navToJob: "Navegar para o Trabalho",
    addressPlaceholder: "Insira o endereço do serviço...",
    titleLabel: "Título do Pedido",
    titlePlaceholder: "ex: Pintura da sala",
    detailsPlaceholder: "Descreva o que precisa de ser feito...",
    whenLabel: "Quando?",
    urgencyAsap: "O mais depressa possível",
    urgencyThisWeek: "Esta semana",
    urgencyPlanning: "Planear com antecedência",
    budgetHelp: "O profissional confirmará o preço final após avaliação.",
    requestQuotes: "Pedir Orçamentos",
    noServices: "Nenhum serviço encontrado para",
    clearSearch: "Limpar Pesquisa",
    proCTA: "É um profissional?",
    proCTADesc: "Junte-se ao Zolver e faça crescer o seu negócio hoje.",
    proCTABtn: "Começar como Pro",
    openCompanyBtn: "Abrir Zolver for Business",
    popularCategories: "Categorias Populares",
    exploreServices: "Encontre os melhores profissionais no Luxemburgo",
    results: "resultados",
    viewAllServices: "Ver Todos os Serviços",
    heroTitle: "Encontre o melhor <span class='text-orange-500'>Pro</span> para qualquer tarefa",
    heroSubtitle: "Reserve profissionais verificados para limpeza, reparações, beleza e muito mais.",
    allServicesTitle: "Todos os Serviços",
    trustSecure: "Pagamentos Seguros",
    trustStars: "Avaliações Verificadas",
    trustFast: "Reserva Instantânea",
    connectPortfolio: "Ligar o seu Portfólio",
    connectPortfolioDesc: "Mostre o seu trabalho diretamente do Instagram no seu perfil.",
    connecting: "A ligar...",
    connectBtn: "Ligar Instagram",
    autoSync: "Sincronização automática ativa",
    instaConnected: "Instagram ligado",
    itemsSynced: "itens sincronizados",
    disconnect: "Desligar",
    noCaption: "Sem legenda.",
    postedOn: "Publicado em",
    wantService: "Quero este serviço",
    statusConfirmed: "Reserva Confirmada",
    subConfirmed: "O profissional chegará à hora marcada.",
    statusEnRoute: "Pro a caminho",
    subEnRoute: "A chegar à sua localização agora.",
    statusArrived: "Pro chegou",
    subArrived: "O profissional está no local.",
    statusInProgress: "Serviço em curso",
    subInProgress: "A tarefa está a ser executada.",
    statusCompleted: "Serviço Concluído",
    subCompleted: "A tarefa foi terminada. Obrigado!",
    recording: "Gravação",
    invoiceNo: "Fatura",
    serviceCompleted: "Serviço Concluído",
    amountHT: "Montante HT",
    downloadPdf: "Descarregar PDF",
    proposalUpdate: "Atualização da Proposta",
    offerAccepted: "Oferta Aceite",
    offerDeclined: "Oferta Recusada",
    acceptOffer: "Aceitar Oferta",
    typeMessage: "Escreva uma mensagem...",
    updateOffer: "Atualizar Oferta",
    newPrice: "Novo Preço",
    reasonChange: "Razão da alteração",
    sendUpdate: "Enviar Atualização",
    generateInvoice: "Gerar Fatura",
    assign: "Atribuir Equipa",
    actionOnWay: "Estou a caminho",
    actionArrived: "Cheguei",
    actionStart: "Commencer",
    finishJob: "Marquer comme Terminé",
    // Workflow - PT
    changeOffer: "Alterar Oferta",
    executionPending: "Pendente",
    executionEnRoute: "A Caminho",
    executionArrived: "Chegou",
    executionInProgress: "Em Progresso",
    executionFinished: "Terminado",
    executionPaid: "Pago",
    executionCompleted: "Concluído",
    confirmService: "Confirmar o fim do serviço?",
    serviceNotDone: "Ainda não feito",
    paymentReceived: "Pagamento Recebido?",
    paymentPending: "Pagamento Pendente",
    archiveChat: "Arquivar Ticket",
    stepperEnRoute: "Partida",
    stepperArrived: "Chegada",
    stepperStart: "Início",
    stepperFinish: "Fim",
    startCodeLabel: "Código de Segurança",
    startCodeEnter: "Digite o código de 4 dígitos",
    invalidCode: "Código Inválido",
    teamAssigned: "Membro da equipe atribuído",
    hireAgain: "Contratar Novamente",
    // Admin
    adminCatalog: "Catalog Management",
    adminCatalogDesc: "Add products and manage fulfillment logic.",
    adminAddProduct: "Add Product",
    adminProduct: "Product",
    adminCategory: "Category",
    adminPrice: "Price",
    adminStock: "Stock",
    adminType: "Type",
    adminActions: "Actions",
    adminInternal: "Internal",
    adminPartner: "Partner",
    adminEditProduct: "Edit Product",
    adminAddNewProduct: "Add New Product",
    adminFulfillment: "Fulfillment",
    monetizationEngine: "Monetization Engine",
    monetizationDesc: "Control fees, plans, and marketing costs globally.",
    saveAllChanges: "Save All Changes",
    platformDefaults: "Platform Defaults",
    defaultCommission: "Default Commission Rate (%)",
    commissionNote: "Applied to all jobs if no specific plan overrides it.",
    paidBoosts: "Paid Boosts (Marketing)",
    boostDuration: "Duration (Days)",
    subTiers: "Professional Subscription Tiers",
    monthlyPrice: "Monthly Price",
    featureList: "Features (JSON or List)",
    onePerLine: "One feature per line",
    noSubPlans: "No subscription plans defined.",
    initDefaultPlans: "Initialize Default Plans",
    ghostMode: "Ghost Mode",
    commandCenter: "COMMAND",
    loggedAsAdmin: "LOGGED AS",
    overviewTab: "Overview",
    storeTab: "Store Manager",
    pricingTab: "Pricing Config",
    livePulse: "Live Pulse",
    totalUsers: "Total Users",
    activeJobsTab: "Active Jobs",
    volumeGmv: "Volume (GMV)",
    topRegion: "Top Region",
    trustSafety: "Trust & Safety",
    pendingVerifications: "Pending Verifications",
    allClear: "All clear. No pending verifications.",
    proApplicant: "PRO APPLICANT",
    businessReg: "Business Reg",
    reject: "REJECT",
    approveVerify: "APPROVE & VERIFY",
    regionalDist: "Regional Distribution",
    dangerZone: "Danger Zone",
    emergencyBroadcast: "EMERGENCY BROADCAST",
    wipeDatabase: "WIPE DATABASE",
    systemLogs: "SYSTEM_LOGS",
    adminMonetization: "Monetization Engine",
    adminMonetizationDesc: "Control fees, plans, and marketing costs globally.",
    adminPaidBoosts: "Paid Boosts (Marketing)",
    adminCommRate: "Commission Rate (%)",
    adminCommRateDesc: "Applied to all jobs if no specific plan overrides it.",
    adminBilling: "Billing",
    adminMonthly: "Monthly",
    loading: "Loading",
    saving: "Saving",
    storeOfficial: "Official Zolver Store",
    storeHeroTitle: "Gear Up Like a Pro",
    storeHeroDesc: "Get official merchandise, high-quality uniforms, and professional grade tools delivered directly to your job site.",
    storeSearchPlaceholder: "Search gear...",
    storeAllProducts: "All Products",
    storeInStock: "in stock",
    storeOutOfStock: "Out of Stock",
    storeOfficialBadge: "OFFICIAL",
    storePartnerBadge: "PARTNER",
    boostHeroTitle: "Boost Your Profile",
    boostHeroDesc: "Get up to 5x more job leads by featuring your profile.",
    boostStatusActive: "Boost Active!",
    boostStatusExpires: "Your profile is boosted until",
    boostBestValue: "BEST VALUE",
    boostSelectPlan: "Select Plan",
    boostSelected: "Selected",
    boostActivateNow: "Activate Boost Now",
    boostDisclaimer: "By activating a boost, you agree to our marketing terms. The boost is applied immediately and is non-refundable.",
    boostStatusExpiresLong: "You are now boosted for",
    days: "days",
    processing: "Processing..."
  },
  de: {
    welcome: "Willkommen bei Zolver",
    findPro: "Profi finden",
    searchPlaceholder: "Welchen Service benötigen Sie?",
    login: "Anmelden",
    logout: "Abmelden",
    signup: "Registrieren",
    profile: "Profil",
    messages: "Nachrichten",
    notifications: "Benachrichtigungen",
    settings: "Einstellungen",
    OPEN: "Offen",
    IN_PROGRESS: "In Bearbeitung",
    COMPLETED: "Abgeschlossen",
    CANCELLED: "Storniert",
    liveMarket: "Live-Markt",
    myRequests: "Meine Anfragen",
    historyTab: "Verlauf",
    teamTab: "Team",
    postJob: "Auftrag posten",
    viewDetails: "Details ansehen",
    accept: "Akzeptieren",
    decline: "Ablehnen",
    hire: "Einstellen",
    total: 'Total',
    cleaning: "Reinigung",
    moving: "Umzug",
    plumbing: "Sanitär",
    electrical: "Elektrik",
    painting: "Maler",
    gardening: "Garten",
    opportunities: "Neue Chancen",
    scanningJobs: "Suche nach Aufträgen in der Nähe...",
    financialErp: "Finanzen & ERP",
    financialPerformance: "Verfolgen Sie Ihre Geschäftsleistung",
    addTransaction: "Transaktion hinzufügen",
    exportReport: "Bericht exportieren",
    breakdown: "Aufschlüsselung",
    noJobsPeriod: "Keine Transaktionen in diesem Zeitraum",
    manageTeam: "Team verwalten",
    manageTeamDesc: "Techniker hinzufügen und verwalten",
    addMember: "Mitglied hinzufügen",
    staffAdded: "Mitarbeiter erfolgreich hinzugefügt",
    saveEmployee: "Mitarbeiter speichern",
    roleTitle: "Rolle & Berechtigungen",
    active: "Aktiv",
    inactive: "Inaktiv",
    fullName: "Vollständiger Name",
    emailLogin: "E-Mail (Login)",
    invBillTo: "Rechnung an",
    invDate: "Datum",
    invDue: "Fälligkeit",
    invDesc: "Beschreibung",
    invQty: "Menge",
    invRate: "Einzelpreis",
    invTotal: "Gesamt",
    invSubtotal: "Zwischensumme",
    invVatAmt: "MwSt Betrag",
    invTotalDue: "Gesamtbetrag",
    invFooter: "Vielen Dank für Ihr Vertrauen!",
    detailsLabel: "Details",
    photosOptional: "Fotos",
    yourOffer: "Ihr Angebot",
    cancel: "Abbrechen",
    saveChanges: "Änderungen speichern",
    today: "Heute",
    yesterday: "Gestern",
    noHistory: "Kein Verlauf verfügbar",
    confirmDelete: "Löschen bestätigen",
    noActiveRequests: "Keine aktiven Anfragen gefunden.",
    signIn: "Anmelden",
    welcomeSubtitle: "Lokale Talente mit Menschen verbinden, die Hilfe benötigen.",
    loginWithEmail: "Mit E-Mail anmelden",
    loginWithPhone: "Mit Telefon anmelden",
    email: "E-Mail",
    phoneLabel: "Telefonnummer",
    password: "Passwort",
    forgotPassword: "Passwort vergessen?",
    dontHaveAccount: "Haben Sie kein Konto?",
    signUp: "Registrieren",
    createAccount: "Konto erstellen",
    loggedAs: "Angemeldet als",
    dashboard: "Dashboard",
    whatNeed: "Was brauchen Sie heute?",
    messagesTab: "Nachrichten",
    manageRequests: "Anfragen verwalten",
    createFirstRequest: "Erste Anfrage erstellen",
    editRequest: "Anfrage bearbeiten",
    deleteRequest: "Anfrage löschen",
    goToMarket: "Zum Markt",
    waitingClient: "Warten auf Kunden",
    acceptAndChat: "Akzeptieren & Chatten",
    noRequestsDesc: "Sie haben noch keine Anfragen. Veröffentlichen Sie eine!",
    favoritesTab: "Favoriten",
    noFavorites: "Noch keine Favoriten",
    instaPortfolio: "Instagram Portfolio",
    clientRole: "Kunde",
    reliableClient: "Zuverlässiger Kunde",
    requestsMade: "Gestellte Anfragen",
    paymentRate: "Zahlungsrate",
    speaks: "Spricht",
    serviceLocation: "Service-Standort",
    openMaps: "In Maps öffnen",
    verifiedBadge: "Verifizierter Profi",
    jobs: "Aufträge",
    onlinePresence: "Online-Präsenz",
    businessHours: "Öffnungszeiten",
    bio: "Bio",
    serviceTimeline: "Service-Verlauf",
    contactInfo: "Kontaktinfo",
    removeFromFavorites: "Aus Favoriten entfernen",
    addToFavorites: "Zu Favoriten hinzufügen",
    unblockContact: "Kontakt entsperren",
    blockContact: "Kontakt sperren",
    hireNow: "Jetzt beauftragen",
    imClient: "Ich bin ein Kunde",
    imPro: "Ich bin ein Profi",
    back: "Zurück",
    noCompany: "Ich habe noch keine Firma",
    personalDetails: "Persönliche Daten",
    businessDetails: "Geschäftsdaten",
    servicesAndScope: "Dienstleistungen & Umfang",
    licenseDetails: "Lizenzdetails",
    financialPlan: "Finanzplan",
    reviewDetails: "Prüfen & Bestätigen",
    stepIndicator: "Schritt {step} von {total}",
    confirmPasswordLabel: "Passwort bestätigen",
    cnsNumber: "CNS-Nummer",
    street: "Straße",
    number: "Nummer",
    floor: "Stockwerk / Whg",
    residence: "Wohnsitz",
    elevator: "Aufzug",
    parking: "Parkplatz",
    addAddress: "Adresse hinzufügen",
    postalCode: "Postleitzahl",
    locality: "Ort",

    idUpload: "Personalausweis / Reisepass",
    attached: "Datei angehängt",
    independant: "Freiberuflich / Selbstständig",
    societe: "Unternehmen (S.à r.l, S.A, etc.)",
    companyName: "Firmenname",
    tvaNumber: "MwSt.-Nummer",
    rcsNumber: "RCS-Nummer",
    selectServices: "Dienstleistungen auswählen",
    selectServicesDesc: "Wählen Sie die Dienste aus, die Sie Kunden anbieten",
    licenseInfo: "Gewerbeschein-Informationen",
    licenseNum: "Lizenznummer",
    licenseExpiry: "Ablaufdatum",
    uploadPdfLabel: "Lizenz hochladen (PDF/Bild)",
    licenseUploaded: "Lizenz erfolgreich hochgeladen",
    planSelect: "Wählen Sie Ihren Plan",
    founderOffer: "Early-Founder-Angebot",
    premiumPlan: "Premium-Profi",
    lifetimeAccess: "Lebenslanger Zugriff",
    benefitSite: "Eigene Profi-Website",
    benefitPriority: "Priorität in den Suchergebnissen",
    benefitFees: "0% Servicegebühren",
    benefitSupport: "Rund-um-die-Uhr Support",
    benefitBadge: "Gründer-Mitglied-Abzeichen",
    durationLabel: "/ Monat",
    freeForever: "Für immer kostenlos",
    basicPlan: "Basis",
    basicDesc: "Perfekt für den Einstieg",
    payoutDetails: "Auszahlungsdetails",
    iban: "IBAN",
    accHolder: "Kontoinhaber",
    paymentMethod: "Zahlungsmethode für das Abonnement",
    paymentValidation: "Prüfen & Sichern",
    expiryDate: "MM/JJ",
    cvc: "CVC",
    cardHolder: "Name des Karteninhabers",
    websiteReady: "Ihre Website ist fertig!",
    websiteDesc: "Wir haben eine professionelle Landingpage für Ihr Unternehmen erstellt.",
    visitSite: "Meine Website besuchen",
    generatedFor: "Erstellt für",
    summaryServices: "Ausgewählte Dienste",
    summaryPlan: "Gewählter Plan",
    summaryIban: "Auszahlungs-IBAN",
    declaration: "Ich erkläre, dass alle Informationen wahr sind",
    finish: "Einrichtung abschließen",
    next: "Weiter",
    welcomeBack: "Willkommen zurück!",
    personalInfo: "Persönliche Informationen",
    manageIdentity: "Identität und Kontaktinfo verwalten",
    languages: "Sprachen",
    addressLogistics: "Adresse & Logistik",
    smartAddress: "Intelligente Adresssuche",
    houseNumber: "Hausnummer",
    security: "Sicherheit",
    blockedUsers: "Blockierte Benutzer",
    noBlockedUsers: "Keine blockierten Benutzer",
    smartReply: "KI-Smart-Reply",
    smartReplyDesc: "Automatisieren Sie Ihre ersten Antworten an Kunden",
    enableAutoReply: "Auto-Antwort aktivieren",
    activationTime: "Aktivierungszeit",
    immediate: "Sofort",
    mins5: "nach 5 Min.",
    mins15: "nach 15 Min.",
    botPersonality: "Bot-Persönlichkeit",
    agilityMode: "Agilität",
    agilityDesc: "Schnell, prägnant und hilfreich",
    dataMode: "Datengetrieben",
    dataDesc: "Fokus auf das Sammeln von Auftragsdetails",
    customMode: "Benutzerdefiniert",
    customDesc: "Schreiben Sie Ihren eigenen Gruß",
    yourMessage: "Ihre Nachricht",
    botMessageCustomDefault: "Hallo! Vielen Dank für Ihre Anfrage. Wie kann ich Ihnen heute helfen?",
    preview: "Vorschau",
    botMessageAgility: "Hallo! Ich bin die Zolver KI. Ich helfe Ihnen beim Einstieg, während der Profi beschäftigt ist.",
    botMessageData: "Hallo! Um ein besseres Angebot zu erstellen, könnten Sie mir bitte mehr über das Projekt erzählen?",
    botMsgFooter: "Zolver KI-Assistent",
    siteStatus: "Website-Status",
    online: "Online",
    offline: "Offline",
    shareWhatsapp: "Auf WhatsApp teilen",
    appearance: "Erscheinungsbild",
    selectTheme: "Design auswählen",
    accentColor: "Akzentfarbe",
    previewSite: "Website-Vorschau",
    siteInfo: "Website-Inhalt",
    siteInfoDesc: "Firmenbeschreibung und Öffnungszeiten aktualisieren",
    visitExternal: "Externe Seite besuchen",
    companyDesc: "Firmenbeschreibung",
    cantEditHelp: "Support kontaktieren, um dies zu ändern",
    workingDays: "Arbeitstage",
    openingTime: "Öffnungszeit",
    closingTime: "Schließzeit",
    subscription: "Abonnement",
    currentPlan: "Aktueller Plan",
    activePlan: "Aktiver Plan",
    upgradeBtn: "Auf Premium upgraden",
    paymentCard: "Zahlungskarte",
    legalForm: "Rechtsform",
    banking: "Bankwesen",
    logisticsNote: "Logistik-Hinweis",
    luxNoteDesc: "Luxemburg-spezifische Logistik",
    clientRoleDesc: "Ich möchte Profis engagieren",
    reliableClientDesc: "Vertrauenswürdiges Community-Mitglied",
    myWebsite: "Meine Website",
    chatSettings: "Chat-Einstellungen",
    themeModern: "Modern",
    themeClassic: "Klassisch",
    themeBold: "Auffällig",
    themeMinimal: "Minimalistisch",
    companyData: "Unternehmensdaten",
    companyLocation: "Unternehmensstandort",
    staffRestriction: "Zugriff eingeschränkt",
    staffRestrictionDesc: "Sie haben keinen Zugriff auf diese Funktion. Bitte kontaktieren Sie Ihren Manager.",
    staffDashboard: "Mitarbeiter-Dashboard",
    navToJob: "Zum Auftrag navigieren",
    addressPlaceholder: "Service-Adresse eingeben...",
    titleLabel: "Titel der Anfrage",
    titlePlaceholder: "z.B. Wohnzimmer streichen",
    detailsPlaceholder: "Beschreiben Sie, was getan werden muss...",
    whenLabel: "Wann?",
    urgencyAsap: "So schnell wie möglich",
    urgencyThisWeek: "Diese Woche",
    urgencyPlanning: "Vorausplanung",
    budgetHelp: "Der Profi wird den Endpreis nach Prüfung bestätigen.",
    requestQuotes: "Angebote anfordern",
    noServices: "Keine Dienstleistungen gefunden für",
    clearSearch: "Suche löschen",
    proCTA: "Sind Sie ein Profi?",
    proCTADesc: "Treten Sie Zolver bei und erweitern Sie Ihr Geschäft noch heute.",
    proCTABtn: "Als Profi starten",
    openCompanyBtn: "Zolver for Business öffnen",
    popularCategories: "Beliebte Kategorien",
    exploreServices: "Finden Sie die besten Profis in Luxemburg",
    results: "Ergebnisse",
    viewAllServices: "Alle Dienstleistungen ansehen",
    heroTitle: "Finden Sie den besten <span class='text-orange-500'>Pro</span> für jede Aufgabe",
    heroSubtitle: "Buchen Sie geprüfte Profis für Reinigung, Reparaturen, Schönheit und mehr.",
    allServicesTitle: "Alle Dienstleistungen",
    trustSecure: "Sichere Zahlungen",
    trustStars: "Verifizierte Bewertungen",
    trustFast: "Sofortbuchung",
    connectPortfolio: "Portfolio verbinden",
    connectPortfolioDesc: "Zeigen Sie Ihre Arbeit direkt von Instagram in Ihrem Profil.",
    connecting: "Verbindung wird hergestellt...",
    connectBtn: "Instagram verbinden",
    autoSync: "Automatische Synchronisierung aktiviert",
    instaConnected: "Instagram verbunden",
    itemsSynced: "Elemente synchronisiert",
    disconnect: "Trennen",
    noCaption: "Keine Bildunterschrift vorhanden.",
    postedOn: "Gepostet am",
    wantService: "Ich möchte diesen Service",
    statusConfirmed: "Buchung bestätigt",
    subConfirmed: "Der Profi wird zum geplanten Zeitpunkt eintreffen.",
    statusEnRoute: "Profi ist unterwegs",
    subEnRoute: "Kommt jetzt zu Ihrem Standort.",
    statusArrived: "Profi ist angekommen",
    subArrived: "Der Profi ist am Standort.",
    statusInProgress: "Dienstleistung in Bearbeitung",
    subInProgress: "Die Aufgabe wird ausgeführt.",
    statusCompleted: "Dienstleistung abgeschlossen",
    subCompleted: "Die Aufgabe wurde beendet. Vielen Dank!",
    recording: "Aufnahme",
    invoiceNo: "Rechnung",
    serviceCompleted: "Dienstleistung abgeschlossen",
    amountHT: "Betrag (zzgl. MwSt.)",
    downloadPdf: "PDF herunterladen",
    proposalUpdate: "Angebotsaktualisierung",
    offerAccepted: "Angebot angenommen",
    offerDeclined: "Angebot abgelehnt",
    acceptOffer: "Angebot annehmen",
    typeMessage: "Nachricht schreiben...",
    updateOffer: "Angebot aktualisieren",
    newPrice: "Neuer Preis",
    reasonChange: "Grund für Änderung",
    sendUpdate: "Update senden",
    generateInvoice: "Rechnung erstellen",
    assign: "Team zuweisen",
    actionOnWay: "Ich bin auf dem Weg",
    actionArrived: "Ich bin angekommen",
    actionStart: "Arbeit Beginnen",
    finishJob: "Als Beendet Markieren",
    // Workflow - DE
    changeOffer: "Angebot Ändern",
    executionPending: "Ausstehend",
    executionEnRoute: "Unterwegs",
    executionArrived: "Angekommen",
    executionInProgress: "In Bearbeitung",
    executionFinished: "Fertig",
    executionPaid: "Bezahlt",
    executionCompleted: "Abgeschlossen",
    confirmService: "Service bestätigen?",
    serviceNotDone: "Noch nicht fertig",
    paymentReceived: "Zahlung erhalten?",
    paymentPending: "Zahlung ausstehend",
    archiveChat: "Ticket Archivieren",
    stepperEnRoute: "Abfahrt",
    stepperArrived: "Ankunft",
    stepperStart: "Start",
    stepperFinish: "Ende",
    startCodeLabel: "Sicherheitscode",
    startCodeEnter: "4-stelligen Code eingeben",
    invalidCode: "Ungültiger Code",
    teamAssigned: "Teammitglied zugewiesen",
    hireAgain: "Erneut Beauftragen",
    // Admin
    adminCatalog: "Catalog Management",
    adminCatalogDesc: "Add products and manage fulfillment logic.",
    adminAddProduct: "Add Product",
    adminProduct: "Product",
    adminCategory: "Category",
    adminPrice: "Price",
    adminStock: "Stock",
    adminType: "Type",
    adminActions: "Actions",
    adminInternal: "Internal",
    adminPartner: "Partner",
    adminEditProduct: "Edit Product",
    adminAddNewProduct: "Add New Product",
    adminFulfillment: "Fulfillment",
    monetizationEngine: "Monetization Engine",
    monetizationDesc: "Control fees, plans, and marketing costs globally.",
    saveAllChanges: "Save All Changes",
    platformDefaults: "Platform Defaults",
    defaultCommission: "Default Commission Rate (%)",
    commissionNote: "Applied to all jobs if no specific plan overrides it.",
    paidBoosts: "Paid Boosts (Marketing)",
    boostDuration: "Duration (Days)",
    subTiers: "Professional Subscription Tiers",
    monthlyPrice: "Monthly Price",
    featureList: "Features (JSON or List)",
    onePerLine: "One feature per line",
    noSubPlans: "No subscription plans defined.",
    initDefaultPlans: "Initialize Default Plans",
    ghostMode: "Ghost Mode",
    commandCenter: "COMMAND",
    loggedAsAdmin: "LOGGED AS",
    overviewTab: "Overview",
    storeTab: "Store Manager",
    pricingTab: "Pricing Config",
    livePulse: "Live Pulse",
    totalUsers: "Total Users",
    activeJobsTab: "Active Jobs",
    volumeGmv: "Volume (GMV)",
    topRegion: "Top Region",
    trustSafety: "Trust & Safety",
    pendingVerifications: "Pending Verifications",
    allClear: "All clear. No pending verifications.",
    proApplicant: "PRO APPLICANT",
    businessReg: "Business Reg",
    reject: "REJECT",
    approveVerify: "APPROVE & VERIFY",
    regionalDist: "Regional Distribution",
    dangerZone: "Danger Zone",
    emergencyBroadcast: "EMERGENCY BROADCAST",
    wipeDatabase: "WIPE DATABASE",
    systemLogs: "SYSTEM_LOGS",
    adminMonetization: "Monetization Engine",
    adminMonetizationDesc: "Control fees, plans, and marketing costs globally.",
    adminPaidBoosts: "Paid Boosts (Marketing)",
    adminCommRate: "Commission Rate (%)",
    adminCommRateDesc: "Applied to all jobs if no specific plan overrides it.",
    adminBilling: "Billing",
    adminMonthly: "Monthly",
    loading: "Loading",
    saving: "Saving",
    storeOfficial: "Official Zolver Store",
    storeHeroTitle: "Gear Up Like a Pro",
    storeHeroDesc: "Get official merchandise, high-quality uniforms, and professional grade tools delivered directly to your job site.",
    storeSearchPlaceholder: "Search gear...",
    storeAllProducts: "All Products",
    storeInStock: "in stock",
    storeOutOfStock: "Out of Stock",
    storeOfficialBadge: "OFFICIAL",
    storePartnerBadge: "PARTNER",
    boostHeroTitle: "Boost Your Profile",
    boostHeroDesc: "Get up to 5x more job leads by featuring your profile.",
    boostStatusActive: "Boost Active!",
    boostStatusExpires: "Your profile is boosted until",
    boostBestValue: "BEST VALUE",
    boostSelectPlan: "Select Plan",
    boostSelected: "Selected",
    boostActivateNow: "Activate Boost Now",
    boostDisclaimer: "By activating a boost, you agree to our marketing terms. The boost is applied immediately and is non-refundable.",
    boostStatusExpiresLong: "You are now boosted for",
    days: "days",
    processing: "Processing..."
  },
  lb: {
    welcome: "Wëllkomm bei Zolver",
    findPro: "Fannt e Profi",
    searchPlaceholder: "Wéi e Service braucht Dir?",
    login: "Aloggen",
    logout: "Ausloggen",
    signup: "Registréieren",
    profile: "Profil",
    messages: "Messagen",
    notifications: "Notifikatiounen",
    settings: "Astellungen",
    OPEN: "Op",
    IN_PROGRESS: "Am Gaang",
    COMPLETED: "Fäerdeg",
    CANCELLED: "Ofgebrach",
    liveMarket: "Live Maart",
    myRequests: "Meng Ufroen",
    historyTab: "Verlaf",
    teamTab: "Equipe",
    postJob: "Aarbecht posten",
    viewDetails: "Detailer kucken",
    accept: "Akzeptéieren",
    decline: "Ofleenen",
    hire: "Engagéieren",
    total: "Total",
    cleaning: "Botzen",
    moving: "Plënnere",
    plumbing: "Sanitär",
    electrical: "Elektresch",
    painting: "Molen",
    gardening: "Gaardenaarbecht",
    opportunities: "Nei Méiglechkeeten",
    scanningJobs: "Sicht no Aarbechten an der Géigend...",
    financialErp: "Finanzen & ERP",
    financialPerformance: "Verfollegt Är Geschäftsleeschtung",
    addTransaction: "Transaktioun dobäisetzen",
    exportReport: "Rapport exportéieren",
    breakdown: "Detailer",
    noJobsPeriod: "Keng Transaktiounen an dëser Period",
    manageTeam: "Equipe verwalten",
    manageTeamDesc: "Techniker dobäisetzen an verwalten",
    addMember: "Member dobäisetzen",
    staffAdded: "Mataarbechter erfollegräich dobäigesat",
    saveEmployee: "Mataarbechter späicheren",
    roleTitle: "Roll & Berechtigungen",
    active: "Aktiv",
    inactive: "Inaktiv",
    fullName: "Ganzen Numm",
    emailLogin: "Email (Login)",
    invBillTo: "Rechnung un",
    invDate: "Datum",
    invDue: "Verfall",
    invDesc: "Beschreiwung",
    invQty: "Quantitéit",
    invRate: "Eenheetspräis",
    invTotal: "Total",
    invSubtotal: "Zwëschenzomm",
    invVatAmt: "TVA Betrag",
    invTotalDue: "Total ze bezuelen",
    invFooter: "Merci fir Äert Vertrauen!",
    detailsLabel: "Detailer",
    photosOptional: "Fotoen",
    yourOffer: "Är Offer",
    cancel: "Ofbriechen",
    saveChanges: "Ännerungen späicheren",
    today: "Haut",
    yesterday: "Gëschter",
    noHistory: "Kee Verlaf verfügbar",
    confirmDelete: "Läschen bestätegen",
    noActiveRequests: "Keng aktiv Ufroen fonnt.",
    signIn: "Aloggen",
    welcomeSubtitle: "Lokal Talenter mat Leit verbannen, déi Hëllef brauchen.",
    loginWithEmail: "Aloggen mat Email",
    loginWithPhone: "Aloggen mat Telefon",
    email: "Email",
    phoneLabel: "Telefonsnummer",
    password: "Passwuert",
    forgotPassword: "Passwuert vergiess?",
    dontHaveAccount: "Hutt Dir kee Kont?",
    signUp: "Registréieren",
    createAccount: "Kont erstellen",
    loggedAs: "Ageloggt als",
    dashboard: "Dashboard",
    whatNeed: "Wat braucht Dir haut?",
    messagesTab: "Messagen",
    manageRequests: "Ufroen verwalten",
    createFirstRequest: "Éischt Ufro erstellen",
    editRequest: "Ufro änneren",
    deleteRequest: "Ufro läschen",
    goToMarket: "Op de Maart",
    waitingClient: "Waarden op Client",
    acceptAndChat: "Akzeptéieren & Chatten",
    noRequestsDesc: "Dir hutt nach keng Ufroen. Fänkt un mat enger ze posten!",
    favoritesTab: "Favoritten",
    noFavorites: "Nach keng Favoritten",
    instaPortfolio: "Instagram Portfolio",
    clientRole: "Client",
    reliableClient: "Verlässleche Client",
    requestsMade: "Ufroe gemaach",
    paymentRate: "Bezuelquote",
    speaks: "Schwätzt",
    serviceLocation: "Service Location",
    openMaps: "A Google Maps opmaachen",
    verifiedBadge: "Verifizéierte Profi",
    jobs: "Aarbechten",
    onlinePresence: "Online Präsenz",
    businessHours: "Ëffnungszäiten",
    bio: "Bio",
    serviceTimeline: "Service Timeline",
    contactInfo: "Kontakt Info",
    removeFromFavorites: "Vun de Favoritten ewechhuelen",
    addToFavorites: "Bei d'Favoritten dobäisetzen",
    unblockContact: "Kontakt entspären",
    blockContact: "Kontakt spären",
    hireNow: "Elo astellen",
    imClient: "Ech sinn e Client",
    imPro: "Ech sinn e Profi",
    back: "Zréck",
    noCompany: "Ech hunn nach keng Firma",
    personalDetails: "Perséinlech Detailer",
    businessDetails: "Betribsdetailer",
    servicesAndScope: "Servicer & Ëmfang",
    licenseDetails: "Lizenzdetailer",
    financialPlan: "Finanzplang",
    reviewDetails: "Iwwerpréiwen & Confirméieren",
    stepIndicator: "Schrëtt {step} vu {total}",
    confirmPasswordLabel: "Passwuert confirméieren",
    cnsNumber: "CNS Nummer",
    street: "Strooss",
    number: "Nummer",
    floor: "Stack / Wunneng",
    residence: "Residenz",
    elevator: "Lift",
    parking: "Opfaart",
    addAddress: "Adress dobäisetzen",
    postalCode: "Postcode",
    locality: "Uertschaft",

    idUpload: "Identitéiskaart / Pass",
    attached: "Fichier bäigefüügt",
    independant: "Selbstännegen / Freelance",
    societe: "Firma (S.à r.l, S.A, etc.)",
    companyName: "Numm vun der Firma",
    tvaNumber: "TVA Nummer",
    rcsNumber: "RCS Nummer",
    selectServices: "Wielt Är Servicer",
    selectServicesDesc: "Wielt d'Servicer déi Dir Clienten ubitt",
    licenseInfo: "Informatioun iwwer d'Handelsermächtegung",
    licenseNum: "Lizenznummer",
    licenseExpiry: "Verfallsdatum",
    uploadPdfLabel: "Lizenz eroplueden (PDF/Bild)",
    licenseUploaded: "Lizenz erfollegräich eropgelueden",
    planSelect: "Wielt Äre Plang",
    founderOffer: "Early Founder Offer",
    premiumPlan: "Premium Profi",
    lifetimeAccess: "Liewenslaangen Zougang",
    benefitSite: "Eegenen Profi-Website",
    benefitPriority: "Prioritéit an de Sichresultater",
    benefitFees: "0% Servicefraisen",
    benefitSupport: "24/7 Support",
    benefitBadge: "Founder Member Badge",
    durationLabel: "/ Mount",
    freeForever: "Fir ëmmer gratis",
    basicPlan: "Basis",
    basicDesc: "Perfekt fir unzefänken",
    payoutDetails: "Detailer fir d'Auszuelung",
    iban: "IBAN",
    accHolder: "Kontoinhaber",
    paymentMethod: "Bezuelmethod fir den Abonnement",
    paymentValidation: "Iwwerpréiwen & Securéieren",
    expiryDate: "MM/JO",
    cvc: "CVC",
    cardHolder: "Numm vum Kaarteninhaber",
    websiteReady: "Äre Website ass fäerdeg!",
    websiteDesc: "Mir hunn eng professionell Landingpage fir Äre Betrib generéiert.",
    visitSite: "Mäi Website besichen",
    generatedFor: "Generéiert fir",
    summaryServices: "Gewielten Servicer",
    summaryPlan: "Gewielten Plang",
    summaryIban: "IBAN fir d'Auszuelung",
    declaration: "Ech deklaréieren datt all Informatioune wouer sinn",
    finish: "Setup ofschléissen",
    next: "Weider",
    welcomeBack: "Wëllkomm zréck!",
    personalInfo: "Perséinlech Informatiounen",
    manageIdentity: "Identitéit a Kontaktinfo verwalten",
    languages: "Sproochen",
    addressLogistics: "Adress & Logistik",
    smartAddress: "Intelligent Adress-Sich",
    houseNumber: "Hausnummer",
    security: "Sécherheet",
    blockedUsers: "Blockéiert Benotzer",
    noBlockedUsers: "Keng blockéiert Benotzer",
    smartReply: "KI Smart Reply",
    smartReplyDesc: "Automatiséiert Är éischt Äntwerten u Clienten",
    enableAutoReply: "Auto-Äntwert aktivéieren",
    activationTime: "Aktivéierungszäit",
    immediate: "Sofort",
    mins5: "no 5 Min.",
    mins15: "no 15 Min.",
    botPersonality: "Bot Perséinlechkeet",
    agilityMode: "Agilitéit",
    agilityDesc: "Schnell, präzis an hëllefsbereet",
    dataMode: "Date-orientéiert",
    dataDesc: "Fokus op d'Sammelen vun Detailer",
    customMode: "Personnaliséiert",
    customDesc: "Schreift Ären eegene Message",
    yourMessage: "Äre Message",
    botMessageCustomDefault: "Moien! Merci fir Är Ufro. Wéi kann ech Iech haut hëllefen?",
    preview: "Preview",
    botMessageAgility: "Moien! Ech sinn d'Zolver KI. Ech hëllefen Iech beim Astig während de Profi besat ass.",
    botMessageData: "Moien! Fir eng besser Offer ze erstellen, kënnt Dir mir méi iwwer de Projet soen?",
    botMsgFooter: "Zolver KI Assistent",
    siteStatus: "Website Status",
    online: "Online",
    offline: "Offline",
    shareWhatsapp: "Op WhatsApp deelen",
    appearance: "Ausgesinn",
    selectTheme: "Design wielen",
    accentColor: "Akzentfaarf",
    previewSite: "Website Preview",
    siteInfo: "Website Inhalt",
    siteInfoDesc: "Beschreiwung an Ëffnungszäiten aktualiséieren",
    visitExternal: "Extern Säit besichen",
    companyDesc: "Beschreiwung vum Betrib",
    cantEditHelp: "Kontaktéiert de Support fir dat ze änneren",
    workingDays: "Aarbechtsdeeg",
    openingTime: "Ëffnungszäit",
    closingTime: "Schlusszäit",
    subscription: "Abonnement",
    currentPlan: "Aktuelle Plang",
    activePlan: "Aktive Plang",
    upgradeBtn: "Upgrade op Premium",
    paymentCard: "Bezuelkaart",
    legalForm: "Rechtsform",
    banking: "Bankgeschäft",
    logisticsNote: "Logistik-Notiz",
    luxNoteDesc: "Lëtzebuerger spezifesch Logistik",
    clientRoleDesc: "Ech wëll Profien engagéieren",
    reliableClientDesc: "Verlässleche Member vun der Communautéit",
    myWebsite: "Mäi Website",
    chatSettings: "Chat-Astellungen",
    themeModern: "Modern",
    themeClassic: "Klassesch",
    themeBold: "Opfälleg",
    themeMinimal: "Minimalistesch",
    companyData: "Betribsdaten",
    companyLocation: "Standuert vum Betrib",
    staffRestriction: "Zougang ageschränkt",
    staffRestrictionDesc: "Dir hutt keen Zougang zu dëser Funktioun. Kontaktéiert w.e.g. Äre Manager.",
    staffDashboard: "Mataarbechter Dashboard",
    navToJob: "Navigéiert bei d'Aarbecht",
    addressPlaceholder: "Gitt d'Adress vum Service an...",
    titleLabel: "Titel vun der Ufro",
    titlePlaceholder: "z.B. Stuff molen",
    detailsPlaceholder: "Beschreift wat gemaach muss ginn...",
    whenLabel: "Wéini?",
    urgencyAsap: "Sou séier wéi méiglech",
    urgencyThisWeek: "Dës Woch",
    urgencyPlanning: "Virausplangung",
    budgetHelp: "De Profi bestätegt de Finale Präis no der Iwwerpréiwung.",
    requestQuotes: "Offere froen",
    noServices: "Keng Servicer fonnt fir",
    clearSearch: "Sich läschen",
    proCTA: "Sidd Dir e Profi?",
    proCTADesc: "Gitt bei Zolver a vergréissert Äre Betrib haut.",
    proCTABtn: "Als Profi ufänken",
    openCompanyBtn: "Zolver for Business opmaachen",
    popularCategories: "Populär Kategorien",
    exploreServices: "Fannt déi bescht Profien zu Lëtzebuerg",
    results: "Resultater",
    viewAllServices: "All Servicer kucken",
    heroTitle: "Fannt de beschte <span class='text-orange-500'>Pro</span> fir all Aufgab",
    heroSubtitle: "Bucht verifizéiert Profien fir Botzen, Reparaturen, Schéinheet a méi.",
    allServicesTitle: "All Servicer",
    trustSecure: "Sécher Bezuelungen",
    trustStars: "Verifizéiert Bewäertungen",
    trustFast: "Instant Booking",
    connectPortfolio: "Portfolio verbannen",
    connectPortfolioDesc: "Weist Är Aarbecht direkt vun Instagram op Ärem Profil.",
    connecting: "Verbënnt...",
    connectBtn: "Instagram verbannen",
    autoSync: "Automatesch Synchroniséierung aktivéiert",
    instaConnected: "Instagram verbonnen",
    itemsSynced: "Elementer synchroniséiert",
    disconnect: "Trennen",
    noCaption: "Keng Iwwerschrëft geliwwert.",
    postedOn: "Gepost den",
    wantService: "Ech wëll dëse Service",
    statusConfirmed: "Buchung bestätegt",
    subConfirmed: "De Profi kënnt zum geplangten Zäitpunkt.",
    statusEnRoute: "Profi ass ënnerwee",
    subEnRoute: "Kënnt elo op Är Plaz.",
    statusArrived: "Profi ass ukomm",
    subArrived: "De Profi ass op der Plaz.",
    statusInProgress: "Service am Gaang",
    subInProgress: "D'Aufgab gëtt ausgeführt.",
    statusCompleted: "Service ofgeschloss",
    subCompleted: "D'Aufgab gouf fäerdeg gemaach. Merci!",
    recording: "Opnam",
    invoiceNo: "Rechnung",
    serviceCompleted: "Service ofgeschloss",
    amountHT: "Betrag (ouni TVA)",
    downloadPdf: "PDF eroflueden",
    proposalUpdate: "Propositioun Update",
    offerAccepted: "Offer ugeholl",
    offerDeclined: "Offer ofgeleent",
    acceptOffer: "Offer unhuelen",
    typeMessage: "Eng Noriicht schreiwen...",
    updateOffer: "Offer aktualiséieren",
    newPrice: "Neie Präis",
    reasonChange: "Grond fir d'Ännerung",
    sendUpdate: "Update schécken",
    generateInvoice: "Rechnung erstellen",
    assign: "Team zouweisen",
    actionOnWay: "Ech sinn ënnerwee",
    actionArrived: "Ech sinn ukomm",
    actionStart: "Aarbecht ufänken",
    finishJob: "Als fäerdeg markéieren",
    // Workflow - LB (ADDED MISSING)
    changeOffer: "Offer änneren",
    executionPending: "Waardend",
    executionEnRoute: "Ënnerwee",
    executionArrived: "Ukomm",
    executionInProgress: "Am Gange",
    executionFinished: "Fäerdeg",
    executionPaid: "Bezuelt",
    executionCompleted: "Ofgeschloss",
    confirmService: "Service bestätegen?",
    serviceNotDone: "Nach net fäerdeg",
    paymentReceived: "Bezuelung kritt?",
    paymentPending: "Bezuelung op",
    archiveChat: "Ticket Archivéieren",
    stepperEnRoute: "Depart",
    stepperArrived: "Ukonft",
    stepperStart: "Start",
    stepperFinish: "Schluss",
    startCodeLabel: "Sécherheetscode",
    startCodeEnter: "Gitt de 4-ziffrige Code an",
    invalidCode: "Ongëltege Code",
    teamAssigned: "Teammember zougewisen",
    hireAgain: "Erëm anstellen",
    // Admin
    adminCatalog: "Catalog Management",
    adminCatalogDesc: "Add products and manage fulfillment logic.",
    adminAddProduct: "Add Product",
    adminProduct: "Product",
    adminCategory: "Category",
    adminPrice: "Price",
    adminStock: "Stock",
    adminType: "Type",
    adminActions: "Actions",
    adminInternal: "Internal",
    adminPartner: "Partner",
    adminEditProduct: "Edit Product",
    adminAddNewProduct: "Add New Product",
    adminFulfillment: "Fulfillment",
    monetizationEngine: "Monetization Engine",
    monetizationDesc: "Control fees, plans, and marketing costs globally.",
    saveAllChanges: "Save All Changes",
    platformDefaults: "Platform Defaults",
    defaultCommission: "Default Commission Rate (%)",
    commissionNote: "Applied to all jobs if no specific plan overrides it.",
    paidBoosts: "Paid Boosts (Marketing)",
    boostDuration: "Duration (Days)",
    subTiers: "Professional Subscription Tiers",
    monthlyPrice: "Monthly Price",
    featureList: "Features (JSON or List)",
    onePerLine: "One feature per line",
    noSubPlans: "No subscription plans defined.",
    initDefaultPlans: "Initialize Default Plans",
    ghostMode: "Ghost Mode",
    commandCenter: "COMMAND",
    loggedAsAdmin: "LOGGED AS",
    overviewTab: "Overview",
    storeTab: "Store Manager",
    pricingTab: "Pricing Config",
    livePulse: "Live Pulse",
    totalUsers: "Total Users",
    activeJobsTab: "Active Jobs",
    volumeGmv: "Volume (GMV)",
    topRegion: "Top Region",
    trustSafety: "Trust & Safety",
    pendingVerifications: "Pending Verifications",
    allClear: "All clear. No pending verifications.",
    proApplicant: "PRO APPLICANT",
    businessReg: "Business Reg",
    reject: "REJECT",
    approveVerify: "APPROVE & VERIFY",
    regionalDist: "Regional Distribution",
    dangerZone: "Danger Zone",
    emergencyBroadcast: "EMERGENCY BROADCAST",
    wipeDatabase: "WIPE DATABASE",
    systemLogs: "SYSTEM_LOGS",
    adminMonetization: "Monetization Engine",
    adminMonetizationDesc: "Control fees, plans, and marketing costs globally.",
    adminPaidBoosts: "Paid Boosts (Marketing)",
    adminCommRate: "Commission Rate (%)",
    adminCommRateDesc: "Applied to all jobs if no specific plan overrides it.",
    adminBilling: "Billing",
    adminMonthly: "Monthly",
    loading: "Loading",
    saving: "Saving",
    storeOfficial: "Official Zolver Store",
    storeHeroTitle: "Gear Up Like a Pro",
    storeHeroDesc: "Get official merchandise, high-quality uniforms, and professional grade tools delivered directly to your job site.",
    storeSearchPlaceholder: "Search gear...",
    storeAllProducts: "All Products",
    storeInStock: "in stock",
    storeOutOfStock: "Out of Stock",
    storeOfficialBadge: "OFFICIAL",
    storePartnerBadge: "PARTNER",
    boostHeroTitle: "Boost Your Profile",
    boostHeroDesc: "Get up to 5x more job leads by featuring your profile.",
    boostStatusActive: "Boost Active!",
    boostStatusExpires: "Your profile is boosted until",
    boostBestValue: "BEST VALUE",
    boostSelectPlan: "Select Plan",
    boostSelected: "Selected",
    boostActivateNow: "Activate Boost Now",
    boostDisclaimer: "By activating a boost, you agree to our marketing terms. The boost is applied immediately and is non-refundable.",
    boostStatusExpiresLong: "You are now boosted for",
    days: "days",
    processing: "Processing..."
  }
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
  tCategory: (cat: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Load language from local storage on mount
  useEffect(() => {
    const storedLang = localStorage.getItem('zolver_language') as Language;
    if (storedLang && Object.keys(translations).includes(storedLang)) {
      setLanguage(storedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('zolver_language', lang);
  };

  const tCategory = (cat: string) => {
    const key = (cat || '').toLowerCase().replace(' ', '') as keyof Translations;
    return translations[language][key] || cat;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t: translations[language], tCategory }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
