
import React, { createContext, useContext, useState, ReactNode } from 'react';
import { CATEGORIES } from '../constants';

export type Language = 'EN' | 'FR' | 'DE' | 'LB' | 'PT';

export const LANGUAGES_LIST: { code: Language; label: string; flag: string }[] = [
  { code: 'FR', label: 'Français', flag: '🇫🇷' },
  { code: 'PT', label: 'Português', flag: '🇧🇷' },
  { code: 'EN', label: 'English', flag: '🇬🇧' },
  { code: 'DE', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'LB', label: 'Lëtzebuergesch', flag: '🇱🇺' },
];

// --- CATEGORY TRANSLATIONS MAP ---
const CATEGORY_TRANSLATIONS: Record<Language, Record<string, string>> = {
    EN: {}, 
    FR: {
        Cleaning: "Nettoyage", Electrician: "Électricien", Plumbing: "Plomberie", Gardening: "Jardinage",
        SolarEnergy: "Énergie Solaire", Painter: "Peintre", Carpenter: "Charpentier", Roofer: "Couvreur",
        HVAC: "Chauffage & Climatisation", Locksmith: "Serrurier", Flooring: "Revêtement de Sol",
        PoolMaintenance: "Entretien Piscine", PestControl: "Lutte Antiparasitaire", InteriorDesign: "Décoration Intérieur",
        Handyman: "Bricoleur", Mason: "Maçon", Welder: "Soudeur", Glazier: "Vitrier", ChimneySweep: "Ramoneur",
        SecuritySys: "Systèmes Sécurité", SmartHome: "Domotique", FengShui: "Consultant Feng Shui", Architect: "Architecte",
        Insulation: "Isolation", Demolition: "Démolition", Mechanic: "Mécanicien", ElectricVehicle: "Véhicule Électrique",
        AutoBody: "Carrosserie", CarWash: "Lavage Auto", Towing: "Remorquage", Micromobility: "Trottinettes & Vélos",
        Moving: "Déménagement", Driver: "Chauffeur Privé", DrivingInstructor: "Moniteur Auto-école", BoatMechanic: "Mécanicien Bateau",
        BikeRepair: "Réparation Vélo", CarDetailing: "Detailing Auto", Logistics: "Logistique / Coursier",
        'IT Support': "Support Informatique", WebDev: "Développeur Web", GraphicDesign: "Graphisme", VideoEditor: "Monteur Vidéo",
        SEO: "Spécialiste SEO", SocialMedia: "Gestionnaire Réseaux Sociaux", DataRecovery: "Récupération Données",
        PhoneRepair: "Réparation Téléphone", ApplianceRepair: "Réparation Électroménager", NetworkAdmin: "Admin Réseau",
        CyberSecurity: "Cybersécurité", Accountant: "Comptable", Translator: "Traducteur", Lawyer: "Avocat",
        Notary: "Notaire", TaxAdvisor: "Conseiller Fiscal", HRConsultant: "Consultant RH", Copywriter: "Rédacteur",
        BusinessCoach: "Coach Affaires", VirtualAssistant: "Assistant Virtuel", EventPlanner: "Organisateur Événements",
        DJ: "DJ & Musique", Photographer: "Photographe", Caterer: "Traiteur", Florist: "Fleuriste", Musician: "Musicien",
        Magician: "Magicien", Bartender: "Barman", WeddingOfficiant: "Officiant Mariage", PartyDecorator: "Décorateur Fête",
        Beauty: "Beauté & Esthétique", "Pet Sitter": "Garde Animaux", Hairdresser: "Coiffeur", MakeupArtist: "Maquilleur",
        PersonalTrainer: "Coach Sportif", Yoga: "Professeur Yoga", Massage: "Massage (Relax)", Babysitter: "Baby-sitter",
        Chef: "Chef à Domicile", Tailor: "Tailleur", Shoemaker: "Cordonnier", PersonalShopper: "Personal Shopper",
        LifeCoach: "Coach de Vie", Astrologer: "Astrologue", TravelPlanner: "Planificateur Voyage", DogWalker: "Promeneur Chien",
        DogTrainer: "Dresseur Chien", Tutor: "Soutien Scolaire", LanguageTutor: "Professeur Langues",
        MusicTeacher: "Professeur Musique", ArtTeacher: "Professeur Art", CodingTutor: "Professeur Code", MathTutor: "Professeur Maths"
    },
    PT: {
        Cleaning: "Limpeza", Electrician: "Eletricista", Plumbing: "Encanador", Gardening: "Jardinagem",
        SolarEnergy: "Energia Solar", Painter: "Pintor", Carpenter: "Carpinteiro", Roofer: "Telhadista",
        HVAC: "AVAC", Locksmith: "Chaveiro", Flooring: "Pisos", PoolMaintenance: "Manutenção Piscina",
        PestControl: "Dedetização", InteriorDesign: "Design Interiores", Handyman: "Marido de Aluguel",
        Mason: "Pedreiro", Welder: "Soldador", Glazier: "Vidraceiro", ChimneySweep: "Limpador Chaminé",
        SecuritySys: "Segurança", SmartHome: "Automação", FengShui: "Feng Shui", Architect: "Arquiteto",
        Insulation: "Isolamento", Demolition: "Demolição", Mechanic: "Mecânico", ElectricVehicle: "Veículo Elétrico",
        AutoBody: "Funilaria", CarWash: "Lava-Rápido", Towing: "Guincho", Micromobility: "Patinetes",
        Moving: "Mudanças", Driver: "Motorista", DrivingInstructor: "Instrutor", BoatMechanic: "Mecânico Barco",
        BikeRepair: "Conserto Bike", CarDetailing: "Estética Auto", Logistics: "Logística", 'IT Support': "Suporte TI",
        WebDev: "Dev Web", GraphicDesign: "Design Gráfico", VideoEditor: "Editor Vídeo", SEO: "SEO",
        SocialMedia: "Social Media", DataRecovery: "Recuperação Dados", PhoneRepair: "Conserto Celular",
        ApplianceRepair: "Eletrodomésticos", NetworkAdmin: "Redes", CyberSecurity: "Cibersegurança",
        Accountant: "Contador", Translator: "Tradutor", Lawyer: "Advogado", Notary: "Cartório", TaxAdvisor: "Consultor Fiscal",
        HRConsultant: "Consultor RH", Copywriter: "Redator", BusinessCoach: "Coach", VirtualAssistant: "Assistente Virtual",
        EventPlanner: "Eventos", DJ: "DJ", Photographer: "Fotógrafo", Caterer: "Buffet", Florist: "Florista",
        Musician: "Músico", Magician: "Mágico", Bartender: "Barman", WeddingOfficiant: "Celebrante",
        PartyDecorator: "Decoração", Beauty: "Beleza", "Pet Sitter": "Pet Sitter", Hairdresser: "Cabeleireiro",
        MakeupArtist: "Maquiador", PersonalTrainer: "Personal Trainer", Yoga: "Yoga", Massage: "Massagem",
        Babysitter: "Babá", Chef: "Chef", Tailor: "Costureira", Shoemaker: "Sapateiro", PersonalShopper: "Personal Shopper",
        LifeCoach: "Life Coach", Astrologer: "Astrólogo", TravelPlanner: "Viagens", DogWalker: "Passeador",
        DogTrainer: "Adestrador", Tutor: "Reforço", LanguageTutor: "Prof. Idiomas", MusicTeacher: "Prof. Música",
        ArtTeacher: "Prof. Arte", CodingTutor: "Prof. Programação", MathTutor: "Prof. Matemática"
    },
    DE: { Cleaning: "Reinigung", Electrician: "Elektriker", Plumbing: "Klempner" }, // Partial Fallback
    LB: { Cleaning: "Botzen", Electrician: "Elektriker", Plumbing: "Installateur" }  // Partial Fallback
};

// --- ENGLISH (Base) ---
const enTranslations = {
    signIn: "Sign In",
    welcomeSubtitle: "Welcome back to Zolver",
    imClient: "I'm a Client",
    imPro: "I'm a Pro",
    myWebsite: "My Website",
    siteStatus: "Site Status",
    online: "ONLINE",
    offline: "OFFLINE",
    copyLink: "Copy Link",
    shareWhatsapp: "Share on WhatsApp",
    appearance: "Appearance",
    selectTheme: "Select Theme",
    accentColor: "Accent Color",
    previewSite: "PREVIEW MY SITE",
    siteInfo: "Did you know?",
    siteInfoDesc: "Your site content (Photos, Reviews, Bio) is automatically synced from your Profile.",
    themeModern: "Modern",
    themeClassic: "Classic",
    themeBold: "Bold",
    themeMinimal: "Minimal",
    visitExternal: "Open in Browser",
    linkCopied: "Link Copied!",
    loginWithEmail: "Email",
    loginWithPhone: "Phone",
    email: "Email",
    phoneLabel: "Phone Number",
    password: "Password",
    confirmPasswordLabel: "Confirm Password",
    forgotPassword: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    loggedAs: "Logged in as",
    dashboard: "Dashboard",
    profile: "Profile",
    logout: "Logout",
    personalDetails: "Personal Details",
    businessDetails: "Business Details",
    servicesAndScope: "Services & Scope",
    licenseDetails: "License Details",
    financialPlan: "Financial Plan",
    reviewDetails: "Review Details",
    fullName: "Full Name",
    cnsNumber: "CNS Number (Matricule)",
    street: "Street",
    houseNumber: "Number",
    postalCode: "Postal Code",
    locality: "Locality",
    idUpload: "Upload ID Card",
    independant: "Independente",
    societe: "Company (S.à r.l.)",
    companyName: "Company Name",
    tvaNumber: "VAT Number",
    rcsNumber: "RCS Number",
    selectServices: "Select your Services",
    selectServicesDesc: "Choose the categories you work in",
    licenseNum: "License Number",
    licenseExpiry: "License Expiry",
    planSelect: "Select your Plan",
    founderOffer: "Founder Offer",
    premiumPlan: "Premium Plan",
    lifetimeAccess: "Lifetime Access",
    benefitSite: "Pro Website + SEO",
    benefitPriority: "Search Priority",
    benefitFees: "0% Commission Fees",
    benefitSupport: "Dedicated Support",
    benefitBadge: "Founding Member Badge",
    durationLabel: "Duration:",
    freeForever: "Free Forever",
    basicPlan: "Basic Plan",
    basicDesc: "Standard platform access",
    payoutDetails: "Payout Details",
    iban: "IBAN",
    accHolder: "Account Holder",
    paymentMethod: "Payment Method",
    expiryDate: "MM/YY",
    cvc: "CVC",
    cardHolder: "Card Holder",
    websiteReady: "Website Ready!",
    websiteDesc: "Your professional site is ready.",
    visitSite: "Visit Site",
    generatedFor: "Generated for",
    declaration: "I declare the information is correct.",
    paymentValidation: "Required for verification. No charge today.",
    back: "Back",
    next: "Next",
    finish: "Finish",
    heroTitle: "Zolver: <span class='text-orange-500'>Solved</span>, good as new.",
    heroSubtitle: "Get quotes in minutes for cleaning, renovation, moving and more. The fastest way to get things done.",
    searchPlaceholder: "What do you need help with?",
    trustSecure: "Verified Pros",
    trustStars: "Top Rated",
    trustFast: "Quick Quotes",
    popularCategories: "Popular Professionals",
    viewAllServices: "View all services",
    allServicesTitle: "Find the ideal specialist",
    exploreServices: "Explore our services",
    results: "Results",
    noServices: "No services found for",
    clearSearch: "Clear search",
    proCTA: "Are you a Pro?",
    proCTADesc: "Join Zolver and grow your business.",
    proCTABtn: "Register as Pro",
    noCompany: "No Company?",
    openCompanyHelpBtn: "We help you start",
    openCompanyBtn: "Start Company",
    sectorHome: "Home & Construction",
    sectorAuto: "Auto & Transport",
    sectorTech: "Tech & Digital",
    sectorBusiness: "Business & Legal",
    sectorEvents: "Events & Party",
    sectorLifestyle: "Lifestyle & Care",
    sectorEducation: "Education & Music",
    whatNeed: "What do you need?",
    describeProblem: "Describe your request",
    whereWhen: "Where & When?",
    defineLocation: "Location and timing",
    photosOptional: "Photos (Optional)",
    helpPro: "Help pros understand better",
    stepXofY: "Step {x} of {y}",
    titleLabel: "Title",
    titlePlaceholder: "e.g. Leaking faucet",
    detailsLabel: "Details",
    detailsPlaceholder: "Describe the issue...",
    addressPlaceholder: "Enter address",
    whenLabel: "When?",
    urgencyAsap: "As soon as possible",
    urgencyThisWeek: "This week",
    urgencyPlanning: "Planning phase",
    budgetLabel: "Budget",
    budgetPlaceholder: "Estimated budget",
    budgetHelp: "This helps pros give better quotes",
    addPhoto: "Add Photo",
    photoTip: "Photos help get more accurate quotes",
    requestQuotes: "Request Quotes",
    saveChanges: "Save Changes",
    myRequests: "My Requests",
    manageRequests: "Manage your service requests",
    createFirstRequest: "Create Request",
    noActiveRequests: "No active requests",
    goToMarket: "Go to Market",
    editRequest: "Edit",
    deleteRequest: "Delete",
    historyTab: "History",
    noRequestsDesc: "No history available",
    financialPerformance: "Financial Dashboard",
    filterToday: "Today",
    filterWeek: "Last 7 Days",
    filterMonth: "Last 30 Days",
    filterYear: "This Year",
    totalEarnings: "Gross Revenue",
    jobsCompleted: "Jobs",
    breakdown: "Transactions",
    noJobsPeriod: "No transactions in this period",
    messagesTab: "Messages",
    radar: "Radar",
    nearby: "Nearby",
    offerLabel: "Offer",
    yourOffer: "Your Offer",
    acceptAndChat: "Accept & Chat",
    availBalance: "Available Balance",
    pendingBalance: "Pending",
    vatEstimate: "VAT Estimate (17%)",
    exportReport: "Export Fiscal Report",
    downloadPdf: "Download PDF",
    invoiceNo: "Invoice N°",
    client: "Client",
    service: "Service",
    amountHT: "Net (HT)",
    amountTTC: "Total (TTC)",
    revenueTrend: "Revenue Trend",
    averageValue: "Avg Ticket",
    addExternalService: "Add External Service",
    externalServiceDef: "External Service",
    selectCategory: "Select Category",
    addTransaction: "Add Transaction",
    methodCash: "Cash",
    methodCard: "Card",
    methodTransfer: "Bank Transfer",
    filterAll: "All",
    methodColumn: "Method",
    actionColumn: "Action",
    provisionTax: "Provision for future tax payment",
    monthlyAgg: "Monthly Aggregation",
    dailyBreak: "Daily Breakdown",
    expandRange: "Try selecting a wider date range.",
    upgradeTitle: "Upgrade to PRO",
    upgradeText: "Unlock full financial dashboard and export tools.",
    serviceAgreed: "Service agreed at",
    chatStarted: "Chat started.",
    msgOnWay: "I am on my way.",
    msgArrived: "I have arrived.",
    msgStarted: "Service started.",
    msgPriceUpdate: "Price updated to",
    proposalUpdate: "Proposal Update",
    offerAccepted: "Offer Accepted",
    offerDeclined: "Offer Declined",
    acceptOffer: "Accept Offer",
    receiptTitle: "Receipt",
    startTime: "Start Time",
    endTime: "End Time",
    duration: "Duration",
    total: "Total",
    actionOnWay: "On My Way",
    actionArrived: "Arrived",
    actionStart: "Start Job",
    actionFinish: "Finish Job",
    serviceCompleted: "Service Completed",
    experienceQuestion: "How was your experience with",
    writeReview: "Write a review...",
    submitReview: "Submit Review",
    finishJob: "Generate Invoice & Finish",
    onlineNow: "Online",
    typeMessage: "Type a message...",
    leaveNegotiation: "Leave Negotiation?",
    leaveNegotiationDesc: "You have an active negotiation.",
    returnToMarket: "Return to Market",
    stayHere: "Stay Here",
    updateOffer: "Update Offer",
    newPrice: "New Price",
    reasonChange: "Reason for change",
    sendUpdate: "Send Update",
    confirmChange: "Confirm Change",
    confirmChangeDesc: "Do you accept the price of",
    confirmChangeSuffix: "?",
    yesConfirm: "Yes, Confirm",
    cancel: "Cancel",
    confirmWorkDone: "Is the job done?",
    confirmWorkDoneDesc: "Pro has marked the job as finished. Please confirm.",
    yesFinished: "Yes, Finished",
    noNotYet: "No, Not Yet",
    confirmPayment: "Did you receive payment?",
    confirmPaymentDesc: "Client has confirmed. Did you get paid?",
    yesReceived: "Yes, Payment Received",
    chatArchived: "Chat Archived",
    reopenChat: "Reopen Chat",
    waitingClient: "Waiting for Client...",
    waitingPayment: "Waiting for Payment...",
    liveFeed: "Live Feed",
    opportunities: "Opportunities",
    liveMarket: "Live Market",
    jobClosed: "Job Closed & Archived.",
    invoiceGen: "Invoice Generated. Waiting for client confirmation.",
    chatReopened: "Chat Reopened.",
    statusConfirmed: "Service Confirmed",
    subConfirmed: "Pro has accepted the request",
    statusEnRoute: "On the Way",
    subEnRoute: "Pro is traveling to location",
    statusArrived: "Arrived",
    subArrived: "Pro is at the location",
    statusInProgress: "In Progress",
    subInProgress: "Service is being performed",
    statusCompleted: "Completed",
    subCompleted: "Service finished",
    personalInfo: "Personal Info",
    companyData: "Company Data",
    addressLogistics: "Address & Logistics",
    security: "Security",
    logisticsNote: "Logistics",
    luxNoteDesc: "Luxembourg logistics info",
    companyDesc: "Manage your company details",
    cantEditHelp: "Some fields are read-only",
    legalForm: "Legal Form",
    govAuth: "Gov Authorization",
    banking: "Banking",
    manageIdentity: "Manage Identity",
    languages: "Languages",
    smartAddress: "Smart Address",
    connectPortfolio: "Connect Instagram",
    connectPortfolioDesc: "Showcase your work directly from Instagram",
    connecting: "Connecting...",
    connectBtn: "Connect",
    autoSync: "Auto Sync",
    instaConnected: "Instagram Connected",
    itemsSynced: "items synced",
    disconnect: "Disconnect",
    noCaption: "No caption",
    postedOn: "Posted on",
    wantService: "I want this service",
    rating: "Rating",
    jobs: "Jobs",
    xp: "XP",
    speaks: "Speaks",
    serviceLocation: "Service Location",
    openMaps: "Open Maps",
    bio: "Bio",
    serviceTimeline: "Service Timeline",
    hireNow: "Hire Now",
    viewInstaBtn: "View Portfolio",
    recording: "Recording",
    clientRole: "Client",
    reliableClient: "Reliable",
    requestsMade: "Requests",
    paymentRate: "Payment Rate",
    subscription: "Subscription & Billing",
    currentPlan: "Current Plan",
    paymentCard: "Payment Card",
    changeCard: "Change Card",
    upgradePro: "Upgrade to PRO",
    upgradeDesc: "Automate your accounting with compliant Luxembourgish invoices.",
    invBillTo: "Bill To",
    invDate: "Invoice Date",
    invDue: "Due Date",
    invDesc: "Description",
    invQty: "Qty",
    invRate: "Rate",
    invTotal: "Total",
    invSubtotal: "Subtotal (HT)",
    invVatAmt: "VAT Amount",
    invTotalDue: "Total Due (TTC)",
    invFooter: "Payment due within 14 days.",
    businessHours: "Business Hours",
    openingTime: "Opening Time",
    closingTime: "Closing Time",
    workingDays: "Working Days",
    addToFavorites: "Add to Favorites",
    removeFromFavorites: "Remove Favorite",
    blockContact: "Block Business",
    unblockContact: "Unblock",
    blockedUsers: "Blocked Users",
    noBlockedUsers: "No blocked users.",
    favoritesTab: "Favorites",
    noFavorites: "No favorites yet.",
    contactInfo: "Contact Info",
    onlinePresence: "Online & Social",
    startDate: "From",
    endDate: "To",
    customRange: "Custom Range",
    roleLabel: "Role:",
    quickAccess: "Quick Access (Demo)",
    orLoginManual: "Or login manual",
    licenseInfo: "This license is issued by the Ministry of the Economy.",
    uploadPdfLabel: "Upload PDF / Photo",
    attached: "Document Attached",
    instaPortfolio: "Instagram Portfolio",
    summaryServices: "Services",
    summaryPlan: "Plan",
    summaryIban: "IBAN",
    activePlan: "(Active)",
    closedDay: "Closed",
    chatSettings: "Chat Settings",
    smartReply: "Smart Reply",
    smartReplyDesc: "Auto-reply when you are busy or driving.",
    activationTime: "Activate if no reply in:",
    immediate: "Immediately",
    mins5: "5 Minutes",
    mins15: "15 Minutes",
    botPersonality: "Bot Personality",
    agilityMode: "Agility (Focus on Speed)",
    agilityDesc: "Inform that you are driving and will reply soon.",
    dataMode: "Data Collection (Recommended)",
    dataDesc: "Ask for photos and details to speed up the quote.",
    customMode: "Custom Message",
    customDesc: "Write your own welcome message.",
    botMsgFooter: "Automated reply - Pro notified.",
    enableAutoReply: "Enable automated responses",
    preview: "Preview",
    yourMessage: "Your Message",
    botMessageAgility: "Hello! I'm the virtual assistant. The professional is currently driving or working. He has received your request and will reply personally ASAP!",
    botMessageData: "Thanks for choosing us! I'm finishing a job right now. To speed things up, could you send photos or describe the issue in more detail here? I'll reply shortly.",
    botMessageCustomDefault: "Welcome! I will be with you shortly.",
    financialErp: "Financial (ERP)",
    scanningJobs: "Scanning for jobs...",
    upgradeNow: "Upgrade Now",
    upgradeBtn: "Upgrade",
    stepIndicator: "Step {step} of {total}",
    licenseUploaded: "LICENSE_UPLOADED.PDF",
    tagPunctual: "Punctual",
    tagClean: "Clean Work",
    tagPro: "Professional",
    tagFriendly: "Friendly",
    tagFair: "Fair Price",
    teamTab: "My Team",
    addMember: "Register Employee",
    editMember: "Edit Employee",
    manageTeam: "Manage Team",
    manageTeamDesc: "HR Dashboard & Field Operations",
    roleTitle: "Role / Job Title",
    emailLogin: "Email (Login)",
    active: "Active",
    inactive: "Inactive",
    fireStaff: "Deactivate",
    staffAdded: "Staff Member Added",
    staffUpdated: "Employee Record Updated",
    assignTech: "Assign Technician",
    assignDesc: "Select who will go to the location.",
    assignedMsg: "The company has assigned technician",
    staffDashboard: "My Jobs",
    staffRestriction: "Access Restricted",
    staffRestrictionDesc: "As a staff member, you only have access to your assigned jobs and chat.",
    navToJob: "Navigate to Job",
    completeJob: "Complete Job",
    jobCompletedBy: "Job completed by technician",
    hrNationality: "Nationality / Origin",
    hrCns: "CNS Matricule",
    hrIdCard: "ID Card / Passport No.",
    hrBirthDate: "Date of Birth",
    hrDataTab: "HR & Legal",
    basicDataTab: "Identity",
    deleteStaff: "Delete Employee",
    deleteStaffConfirm: "Are you sure you want to remove this employee? This action cannot be undone.",
    uploadPhoto: "Employee Photo",
    saveEmployee: "Save Record",
    verifiedBadge: "Verified Employee"
};

const ptTranslations: typeof enTranslations = {
    signIn: "Entrar",
    welcomeSubtitle: "Bem-vindo de volta ao Zolver",
    imClient: "Sou Cliente",
    imPro: "Sou Profissional",
    myWebsite: "Meu Site",
    siteStatus: "Status do Site",
    online: "ONLINE",
    offline: "OFFLINE",
    copyLink: "Copiar Link",
    shareWhatsapp: "Compartilhar WhatsApp",
    appearance: "Aparência",
    selectTheme: "Selecionar Tema",
    accentColor: "Cor de Destaque",
    previewSite: "VISUALIZAR MEU SITE",
    siteInfo: "Você sabia?",
    siteInfoDesc: "O conteúdo do seu site (Fotos, Avaliações, Bio) é sincronizado automaticamente do seu Perfil.",
    themeModern: "Moderno",
    themeClassic: "Clássico",
    themeBold: "Arrojado",
    themeMinimal: "Minimalista",
    visitExternal: "Abrir no Navegador",
    linkCopied: "Link Copiado!",
    loginWithEmail: "E-mail",
    loginWithPhone: "Telefone",
    email: "E-mail",
    phoneLabel: "Número de Telefone",
    password: "Senha",
    confirmPasswordLabel: "Confirmar Senha",
    forgotPassword: "Esqueceu a Senha?",
    dontHaveAccount: "Não tem uma conta?",
    signUp: "Cadastre-se",
    loggedAs: "Logado como",
    dashboard: "Painel",
    profile: "Perfil",
    logout: "Sair",
    personalDetails: "Dados Pessoais",
    businessDetails: "Dados da Empresa",
    servicesAndScope: "Serviços & Área",
    licenseDetails: "Licença & Alvará",
    financialPlan: "Plano Financeiro",
    reviewDetails: "Revisão",
    fullName: "Nome Completo",
    cnsNumber: "Número CNS (Matrícula)",
    street: "Rua",
    houseNumber: "Número",
    postalCode: "Código Postal",
    locality: "Localidade",
    idUpload: "Enviar Documento (ID)",
    independant: "Independente",
    societe: "Empresa (S.à r.l.)",
    companyName: "Nome da Empresa",
    tvaNumber: "Número de TVA",
    rcsNumber: "Número RCS",
    selectServices: "Selecione seus Serviços",
    selectServicesDesc: "Escolha as categorias em que atua",
    licenseNum: "Número da Licença",
    licenseExpiry: "Validade da Licença",
    planSelect: "Selecione seu Plano",
    founderOffer: "Oferta de Fundador",
    premiumPlan: "Plano Premium",
    lifetimeAccess: "Acesso Vitalício",
    benefitSite: "Site Pro + SEO",
    benefitPriority: "Prioridade na Busca",
    benefitFees: "0% Taxa de Comissão",
    benefitSupport: "Suporte Dedicado",
    benefitBadge: "Selo Membro Fundador",
    durationLabel: "Duração:",
    freeForever: "Grátis para Sempre",
    basicPlan: "Plano Básico",
    basicDesc: "Acesso padrão à plataforma",
    payoutDetails: "Dados de Recebimento",
    iban: "IBAN",
    accHolder: "Titular da Conta",
    paymentMethod: "Método de Pagamento",
    expiryDate: "MM/AA",
    cvc: "CVC",
    cardHolder: "Titular do Cartão",
    websiteReady: "Site Pronto!",
    websiteDesc: "Seu site profissional está pronto.",
    visitSite: "Visitar Site",
    generatedFor: "Gerado para",
    declaration: "Declaro que as informações estão corretas.",
    paymentValidation: "Necessário para verificação. Nenhuma cobrança hoje.",
    back: "Voltar",
    next: "Próximo",
    finish: "Finalizar",
    heroTitle: "Zolver: <span class='text-orange-500'>Resolveu</span>, tá novo.",
    heroSubtitle: "Receba orçamentos em minutos para limpeza, reformas, mudanças e mais. O jeito mais rápido de resolver.",
    searchPlaceholder: "Do que você precisa?",
    trustSecure: "Verificados",
    trustStars: "Bem Avaliados",
    trustFast: "Rápido",
    popularCategories: "Profissionais Populares",
    viewAllServices: "Ver todos os serviços",
    allServicesTitle: "Encontre o especialista ideal",
    exploreServices: "Explore nossos serviços",
    results: "Resultados",
    noServices: "Nenhum serviço encontrado para",
    clearSearch: "Limpar busca",
    proCTA: "É um Profissional?",
    proCTADesc: "Junte-se à Zolver e cresça seu negócio.",
    proCTABtn: "Registrar como Pro",
    noCompany: "Sem Empresa?",
    openCompanyHelpBtn: "Ajudamos a abrir",
    openCompanyBtn: "Abrir Empresa",
    sectorHome: "Casa & Construção",
    sectorAuto: "Auto & Transporte",
    sectorTech: "Tech & Digital",
    sectorBusiness: "Negócios & Legal",
    sectorEvents: "Eventos & Festas",
    sectorLifestyle: "Estilo de Vida",
    sectorEducation: "Educação & Música",
    whatNeed: "O que você precisa?",
    describeProblem: "Descreva seu pedido",
    whereWhen: "Onde & Quando?",
    defineLocation: "Localização e horário",
    photosOptional: "Fotos (Opcional)",
    helpPro: "Ajude o profissional a entender melhor",
    stepXofY: "Passo {x} de {y}",
    titleLabel: "Título",
    titlePlaceholder: "Ex: Torneira vazando",
    detailsLabel: "Detalhes",
    detailsPlaceholder: "Descreva o problema...",
    addressPlaceholder: "Digite o endereço",
    whenLabel: "Quando?",
    urgencyAsap: "O mais rápido possível",
    urgencyThisWeek: "Esta semana",
    urgencyPlanning: "Fase de planejamento",
    budgetLabel: "Orçamento",
    budgetPlaceholder: "Orçamento estimado",
    budgetHelp: "Isso ajuda a obter orçamentos melhores",
    addPhoto: "Adicionar Foto",
    photoTip: "Fotos ajudam a ter orçamentos mais precisos",
    requestQuotes: "Pedir Orçamentos",
    saveChanges: "Salvar Alterações",
    myRequests: "Meus Pedidos",
    manageRequests: "Gerencie seus pedidos de serviço",
    createFirstRequest: "Criar Pedido",
    noActiveRequests: "Sem pedidos ativos",
    goToMarket: "Ir ao Mercado",
    editRequest: "Editar",
    deleteRequest: "Excluir",
    historyTab: "Histórico",
    noRequestsDesc: "Nenhum histórico disponível",
    financialPerformance: "Painel Financeiro",
    filterToday: "Hoje",
    filterWeek: "Últimos 7 Dias",
    filterMonth: "Últimos 30 Dias",
    filterYear: "Este Ano",
    totalEarnings: "Receita Bruta",
    jobsCompleted: "Trabalhos",
    breakdown: "Transações",
    noJobsPeriod: "Nenhuma transação neste período",
    messagesTab: "Mensagens",
    radar: "Radar",
    nearby: "Próximos",
    offerLabel: "Oferta",
    yourOffer: "Sua Oferta",
    acceptAndChat: "Aceitar & Conversar",
    availBalance: "Saldo Disponível",
    pendingBalance: "Pendente",
    vatEstimate: "Estimativa TVA (17%)",
    exportReport: "Exportar Relatório Fiscal",
    downloadPdf: "Baixar PDF",
    invoiceNo: "Fatura N°",
    client: "Cliente",
    service: "Serviço",
    amountHT: "Líquido (HT)",
    amountTTC: "Total (TTC)",
    revenueTrend: "Tendência de Receita",
    averageValue: "Ticket Médio",
    addExternalService: "Adicionar Serviço Externo",
    externalServiceDef: "Serviço Externo",
    selectCategory: "Selecionar Categoria",
    addTransaction: "Adicionar Transação",
    methodCash: "Dinheiro",
    methodCard: "Cartão",
    methodTransfer: "Transferência",
    filterAll: "Todos",
    methodColumn: "Método",
    actionColumn: "Ação",
    provisionTax: "Provisão para pagamento futuro de impostos",
    monthlyAgg: "Agregação Mensal",
    dailyBreak: "Detalhamento Diário",
    expandRange: "Tente selecionar um intervalo de datas maior.",
    upgradeTitle: "Faça Upgrade para PRO",
    upgradeText: "Desbloqueie o painel financeiro completo e ferramentas de exportação.",
    serviceAgreed: "Serviço acordado em",
    chatStarted: "Chat iniciado.",
    msgOnWay: "Estou a caminho.",
    msgArrived: "Cheguei ao local.",
    msgStarted: "Serviço iniciado.",
    msgPriceUpdate: "Preço atualizado para",
    proposalUpdate: "Atualização da Proposta",
    offerAccepted: "Oferta Aceita",
    offerDeclined: "Oferta Recusada",
    acceptOffer: "Aceitar Oferta",
    receiptTitle: "Recibo",
    startTime: "Hora Início",
    endTime: "Hora Fim",
    duration: "Duração",
    total: "Total",
    actionOnWay: "A Caminho",
    actionArrived: "Cheguei",
    actionStart: "Iniciar Trabalho",
    actionFinish: "Finalizar Trabalho",
    serviceCompleted: "Serviço Concluído",
    experienceQuestion: "Como foi sua experiência com",
    writeReview: "Escreva uma avaliação...",
    submitReview: "Enviar Avaliação",
    finishJob: "Gerar Fatura & Finalizar",
    onlineNow: "Online",
    typeMessage: "Digite uma mensagem...",
    leaveNegotiation: "Sair da Negociação?",
    leaveNegotiationDesc: "Você tem uma negociação ativa.",
    returnToMarket: "Voltar ao Mercado",
    stayHere: "Ficar Aqui",
    updateOffer: "Atualizar Oferta",
    newPrice: "Novo Preço",
    reasonChange: "Motivo da alteração",
    sendUpdate: "Enviar Atualização",
    confirmChange: "Confirmar Alteração",
    confirmChangeDesc: "Você aceita o preço de",
    confirmChangeSuffix: "?",
    yesConfirm: "Sim, Confirmar",
    cancel: "Cancelar",
    confirmWorkDone: "O trabalho foi concluído?",
    confirmWorkDoneDesc: "O profissional marcou o trabalho como finalizado. Por favor, confirme.",
    yesFinished: "Sim, Finalizado",
    noNotYet: "Não, Ainda não",
    confirmPayment: "Você recebeu o pagamento?",
    confirmPaymentDesc: "O cliente confirmou. Você recebeu o pagamento?",
    yesReceived: "Sim, Recebido",
    chatArchived: "Chat Arquivado",
    reopenChat: "Reabrir Chat",
    waitingClient: "Aguardando Cliente...",
    waitingPayment: "Aguardando Pagamento...",
    liveFeed: "Feed ao Vivo",
    opportunities: "Oportunidades",
    liveMarket: "Mercado ao Vivo",
    jobClosed: "Trabalho Fechado & Arquivado.",
    invoiceGen: "Fatura Gerada. Aguardando confirmação do cliente.",
    chatReopened: "Chat Reaberto.",
    statusConfirmed: "Serviço Confirmado",
    subConfirmed: "Profissional aceitou o pedido",
    statusEnRoute: "A Caminho",
    subEnRoute: "Profissional está se deslocando",
    statusArrived: "Chegou",
    subArrived: "Profissional está no local",
    statusInProgress: "Em Andamento",
    subInProgress: "Serviço está sendo realizado",
    statusCompleted: "Concluído",
    subCompleted: "Serviço finalizado",
    personalInfo: "Informações Pessoais",
    companyData: "Dados da Empresa",
    addressLogistics: "Endereço & Logística",
    security: "Segurança",
    logisticsNote: "Logística",
    luxNoteDesc: "Info logística Luxemburgo",
    companyDesc: "Gerencie os detalhes da sua empresa",
    cantEditHelp: "Alguns campos são apenas leitura",
    legalForm: "Forma Legal",
    govAuth: "Autorização Gov",
    banking: "Bancário",
    manageIdentity: "Gerenciar Identidade",
    languages: "Idiomas",
    smartAddress: "Endereço Inteligente",
    connectPortfolio: "Conectar Instagram",
    connectPortfolioDesc: "Mostre seu trabalho diretamente do Instagram",
    connecting: "Conectando...",
    connectBtn: "Conectar",
    autoSync: "Sincronização Auto",
    instaConnected: "Instagram Conectado",
    itemsSynced: "itens sincronizados",
    disconnect: "Desconectar",
    noCaption: "Sem legenda",
    postedOn: "Postado em",
    wantService: "Quero este serviço",
    rating: "Avaliação",
    jobs: "Trabalhos",
    xp: "XP",
    speaks: "Fala",
    serviceLocation: "Local do Serviço",
    openMaps: "Abrir Mapas",
    bio: "Bio",
    serviceTimeline: "Linha do Tempo",
    hireNow: "Contratar Agora",
    viewInstaBtn: "Ver Portfólio",
    recording: "Gravando",
    clientRole: "Cliente",
    reliableClient: "Confiável",
    requestsMade: "Pedidos",
    paymentRate: "Taxa de Pagto",
    subscription: "Assinatura & Faturamento",
    currentPlan: "Plano Atual",
    paymentCard: "Cartão de Pagamento",
    changeCard: "Alterar Cartão",
    upgradePro: "Upgrade para PRO",
    upgradeDesc: "Automatize sua contabilidade com faturas luxemburguesas compatíveis.",
    invBillTo: "Faturar Para",
    invDate: "Data da Fatura",
    invDue: "Vencimento",
    invDesc: "Descrição",
    invQty: "Qtd",
    invRate: "Taxa",
    invTotal: "Total",
    invSubtotal: "Subtotal (HT)",
    invVatAmt: "Valor TVA",
    invTotalDue: "Total Devido (TTC)",
    invFooter: "Pagamento devido em 14 dias.",
    businessHours: "Horário de Funcionamento",
    openingTime: "Abertura",
    closingTime: "Fechamento",
    workingDays: "Dias Úteis",
    addToFavorites: "Adicionar aos Favoritos",
    removeFromFavorites: "Remover Favorito",
    blockContact: "Bloquear Empresa",
    unblockContact: "Desbloquear",
    blockedUsers: "Usuários Bloqueados",
    noBlockedUsers: "Nenhum usuário bloqueado.",
    favoritesTab: "Favoritos",
    noFavorites: "Nenhum favorito ainda.",
    contactInfo: "Informações de Contato",
    onlinePresence: "Online & Social",
    startDate: "De",
    endDate: "Até",
    customRange: "Intervalo Personalizado",
    roleLabel: "Função:",
    quickAccess: "Acesso Rápido (Demo)",
    orLoginManual: "Ou login manual",
    licenseInfo: "Esta licença é emitida pelo Ministério da Economia.",
    uploadPdfLabel: "Enviar PDF / Foto",
    attached: "Documento Anexado",
    instaPortfolio: "Portfólio Instagram",
    summaryServices: "Serviços",
    summaryPlan: "Plano",
    summaryIban: "IBAN",
    activePlan: "(Ativo)",
    closedDay: "Fechado",
    chatSettings: "Configurações de Chat",
    smartReply: "Resposta Inteligente",
    smartReplyDesc: "Resposta automática quando você estiver ocupado ou dirigindo.",
    activationTime: "Ativar se sem resposta em:",
    immediate: "Imediatamente",
    mins5: "5 Minutos",
    mins15: "15 Minutos",
    botPersonality: "Personalidade do Bot",
    agilityMode: "Agilidade (Foco na Velocidade)",
    agilityDesc: "Informa que você está dirigindo e responderá em breve.",
    dataMode: "Coleta de Dados (Recomendado)",
    dataDesc: "Pede fotos e detalhes para acelerar o orçamento.",
    customMode: "Mensagem Personalizada",
    customDesc: "Escreva sua própria mensagem de boas-vindas.",
    botMsgFooter: "Resposta automática - Profissional notificado.",
    enableAutoReply: "Habilitar respostas automáticas",
    preview: "Pré-visualização",
    yourMessage: "Sua Mensagem",
    botMessageAgility: "Olá! Sou o assistente virtual. O profissional está dirigindo ou trabalhando no momento. Ele recebeu seu pedido e responderá pessoalmente o mais rápido possível!",
    botMessageData: "Obrigado por nos escolher! Estou terminando um trabalho agora. Para agilizar, poderia enviar fotos ou descrever o problema com mais detalhes aqui? Responderei em breve.",
    botMessageCustomDefault: "Bem-vindo! Estarei com você em breve.",
    financialErp: "Financeiro (ERP)",
    scanningJobs: "Procurando trabalhos...",
    upgradeNow: "Fazer Upgrade",
    upgradeBtn: "Upgrade",
    stepIndicator: "Passo {step} de {total}",
    licenseUploaded: "LICENCA_ENVIADA.PDF",
    tagPunctual: "Pontual",
    tagClean: "Trabalho Limpo",
    tagPro: "Profissional",
    tagFriendly: "Amigável",
    tagFair: "Preço Justo",
    teamTab: "Minha Equipe",
    addMember: "Registrar Funcionário",
    editMember: "Editar Funcionário",
    manageTeam: "Gerenciar Equipe",
    manageTeamDesc: "Painel de RH & Operações de Campo",
    roleTitle: "Cargo / Função",
    emailLogin: "E-mail (Login)",
    active: "Ativo",
    inactive: "Inativo",
    fireStaff: "Desativar",
    staffAdded: "Membro da equipe adicionado",
    staffUpdated: "Registro do funcionário atualizado",
    assignTech: "Atribuir Técnico",
    assignDesc: "Selecione quem irá ao local.",
    assignedMsg: "A empresa atribuiu o técnico",
    staffDashboard: "Meus Trabalhos",
    staffRestriction: "Acesso Restrito",
    staffRestrictionDesc: "Como membro da equipe, você tem acesso apenas aos seus trabalhos atribuídos e chat.",
    navToJob: "Navegar para o Trabalho",
    completeJob: "Concluir Trabalho",
    jobCompletedBy: "Trabalho concluído pelo técnico",
    hrNationality: "Nacionalidade / Origem",
    hrCns: "Matrícula CNS",
    hrIdCard: "Cartão ID / Passaporte",
    hrBirthDate: "Data de Nascimento",
    hrDataTab: "RH & Legal",
    basicDataTab: "Identidade",
    deleteStaff: "Excluir Funcionário",
    deleteStaffConfirm: "Tem certeza de que deseja remover este funcionário? Esta ação não pode ser desfeita.",
    uploadPhoto: "Foto do Funcionário",
    saveEmployee: "Salvar Registro",
    verifiedBadge: "Funcionário Verificado"
};

const frTranslations: typeof enTranslations = {
    signIn: "Se connecter",
    welcomeSubtitle: "Bienvenue sur Zolver",
    imClient: "Je suis Client",
    imPro: "Je suis Pro",
    myWebsite: "Mon Site Web",
    siteStatus: "Statut du Site",
    online: "EN LIGNE",
    offline: "HORS LIGNE",
    copyLink: "Copier le lien",
    shareWhatsapp: "Partager sur WhatsApp",
    appearance: "Apparence",
    selectTheme: "Sélectionner un thème",
    accentColor: "Couleur d'accent",
    previewSite: "APERÇU DE MON SITE",
    siteInfo: "Le saviez-vous ?",
    siteInfoDesc: "Le contenu de votre site (Photos, Avis, Bio) est automatiquement synchronisé depuis votre profil.",
    themeModern: "Moderne",
    themeClassic: "Classique",
    themeBold: "Audacieux",
    themeMinimal: "Minimaliste",
    visitExternal: "Ouvrir dans le navigateur",
    linkCopied: "Lien copié !",
    loginWithEmail: "Email",
    loginWithPhone: "Téléphone",
    email: "Email",
    phoneLabel: "Numéro de téléphone",
    password: "Mot de passe",
    confirmPasswordLabel: "Confirmer le mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    dontHaveAccount: "Pas encore de compte ?",
    signUp: "S'inscrire",
    loggedAs: "Connecté en tant que",
    dashboard: "Tableau de bord",
    profile: "Profil",
    logout: "Se déconnecter",
    personalDetails: "Détails personnels",
    businessDetails: "Détails de l'entreprise",
    servicesAndScope: "Services & Périmètre",
    licenseDetails: "Détails de la licence",
    financialPlan: "Plan financier",
    reviewDetails: "Révision",
    fullName: "Nom complet",
    cnsNumber: "Numéro CNS (Matricule)",
    street: "Rue",
    houseNumber: "Numéro",
    postalCode: "Code Postal",
    locality: "Localité",
    idUpload: "Télécharger la carte d'identité",
    independant: "Indépendant",
    societe: "Société (S.à r.l.)",
    companyName: "Nom de la société",
    tvaNumber: "Numéro de TVA",
    rcsNumber: "Numéro RCS",
    selectServices: "Sélectionnez vos services",
    selectServicesDesc: "Choisissez les catégories dans lesquelles vous travaillez",
    licenseNum: "Numéro de licence",
    licenseExpiry: "Expiration de la licence",
    planSelect: "Sélectionnez votre plan",
    founderOffer: "Offre Fondateur",
    premiumPlan: "Plan Premium",
    lifetimeAccess: "Accès à vie",
    benefitSite: "Site Pro + SEO",
    benefitPriority: "Priorité de recherche",
    benefitFees: "0% de frais de commission",
    benefitSupport: "Support dédié",
    benefitBadge: "Badge Membre Fondateur",
    durationLabel: "Durée :",
    freeForever: "Gratuit pour toujours",
    basicPlan: "Plan Basique",
    basicDesc: "Accès standard à la plateforme",
    payoutDetails: "Détails de paiement",
    iban: "IBAN",
    accHolder: "Titulaire du compte",
    paymentMethod: "Méthode de paiement",
    expiryDate: "MM/AA",
    cvc: "CVC",
    cardHolder: "Titulaire de la carte",
    websiteReady: "Site Web Prêt !",
    websiteDesc: "Votre site professionnel est prêt.",
    visitSite: "Visiter le site",
    generatedFor: "Généré pour",
    declaration: "Je déclare que les informations sont correctes.",
    paymentValidation: "Requis pour vérification. Aucun frais aujourd'hui.",
    back: "Retour",
    next: "Suivant",
    finish: "Terminer",
    heroTitle: "Zolver: <span class='text-orange-500'>Résolu</span>, comme neuf.",
    heroSubtitle: "Obtenez des devis en quelques minutes pour le nettoyage, la rénovation, le déménagement et plus encore.",
    searchPlaceholder: "De quoi avez-vous besoin ?",
    trustSecure: "Pros Vérifiés",
    trustStars: "Mieux Notés",
    trustFast: "Devis Rapides",
    popularCategories: "Professionnels Populaires",
    viewAllServices: "Voir tous les services",
    allServicesTitle: "Trouvez le spécialiste idéal",
    exploreServices: "Explorez nos services",
    results: "Résultats",
    noServices: "Aucun service trouvé pour",
    clearSearch: "Effacer la recherche",
    proCTA: "Vous êtes un Pro ?",
    proCTADesc: "Rejoignez Zolver et développez votre activité.",
    proCTABtn: "S'inscrire comme Pro",
    noCompany: "Pas de société ?",
    openCompanyHelpBtn: "Nous vous aidons à démarrer",
    openCompanyBtn: "Créer une société",
    sectorHome: "Maison & Construction",
    sectorAuto: "Auto & Transport",
    sectorTech: "Tech & Numérique",
    sectorBusiness: "Affaires & Juridique",
    sectorEvents: "Événements & Fêtes",
    sectorLifestyle: "Style de vie & Soins",
    sectorEducation: "Éducation & Musique",
    whatNeed: "De quoi avez-vous besoin ?",
    describeProblem: "Décrivez votre demande",
    whereWhen: "Où & Quand ?",
    defineLocation: "Lieu et horaire",
    photosOptional: "Photos (Optionnel)",
    helpPro: "Aidez le pro à mieux comprendre",
    stepXofY: "Étape {x} sur {y}",
    titleLabel: "Titre",
    titlePlaceholder: "Ex : Robinet qui fuit",
    detailsLabel: "Détails",
    detailsPlaceholder: "Décrivez le problème...",
    addressPlaceholder: "Entrez l'adresse",
    whenLabel: "Quand ?",
    urgencyAsap: "Dès que possible",
    urgencyThisWeek: "Cette semaine",
    urgencyPlanning: "Phase de planification",
    budgetLabel: "Budget",
    budgetPlaceholder: "Budget estimé",
    budgetHelp: "Cela aide les pros à donner de meilleurs devis",
    addPhoto: "Ajouter une photo",
    photoTip: "Les photos aident à obtenir des devis plus précis",
    requestQuotes: "Demander des devis",
    saveChanges: "Enregistrer",
    myRequests: "Mes demandes",
    manageRequests: "Gérez vos demandes de service",
    createFirstRequest: "Créer une demande",
    noActiveRequests: "Aucune demande active",
    goToMarket: "Aller au marché",
    editRequest: "Modifier",
    deleteRequest: "Supprimer",
    historyTab: "Historique",
    noRequestsDesc: "Aucun historique disponible",
    financialPerformance: "Tableau de Bord Financier",
    filterToday: "Aujourd'hui",
    filterWeek: "7 derniers jours",
    filterMonth: "30 derniers jours",
    filterYear: "Cette année",
    totalEarnings: "Revenu Brut",
    jobsCompleted: "Emplois",
    breakdown: "Transactions",
    noJobsPeriod: "Aucune transaction sur cette période",
    messagesTab: "Messages",
    radar: "Radar",
    nearby: "À proximité",
    offerLabel: "Offre",
    yourOffer: "Votre offre",
    acceptAndChat: "Accepter & Discuter",
    availBalance: "Solde disponible",
    pendingBalance: "En attente",
    vatEstimate: "Estimation TVA (17%)",
    exportReport: "Exporter le rapport fiscal",
    downloadPdf: "Télécharger PDF",
    invoiceNo: "Facture N°",
    client: "Client",
    service: "Service",
    amountHT: "Net (HT)",
    amountTTC: "Total (TTC)",
    revenueTrend: "Tendance des revenus",
    averageValue: "Panier moyen",
    addExternalService: "Ajouter un service externe",
    externalServiceDef: "Service externe",
    selectCategory: "Sélectionner une catégorie",
    addTransaction: "Ajouter une transaction",
    methodCash: "Espèces",
    methodCard: "Carte",
    methodTransfer: "Virement",
    filterAll: "Tous",
    methodColumn: "Méthode",
    actionColumn: "Action",
    provisionTax: "Provision pour paiement futur des impôts",
    monthlyAgg: "Agrégation mensuelle",
    dailyBreak: "Répartition quotidienne",
    expandRange: "Essayez de sélectionner une plage de dates plus large.",
    upgradeTitle: "Passez à PRO",
    upgradeText: "Débloquez le tableau de bord financier complet et les outils d'exportation.",
    serviceAgreed: "Service convenu à",
    chatStarted: "Discussion commencée.",
    msgOnWay: "Je suis en route.",
    msgArrived: "Je suis arrivé.",
    msgStarted: "Service commencé.",
    msgPriceUpdate: "Prix mis à jour à",
    proposalUpdate: "Mise à jour de la proposition",
    offerAccepted: "Offre acceptée",
    offerDeclined: "Offre refusée",
    acceptOffer: "Accepter l'offre",
    receiptTitle: "Reçu",
    startTime: "Heure de début",
    endTime: "Heure de fin",
    duration: "Durée",
    total: "Total",
    actionOnWay: "En route",
    actionArrived: "Arrivé",
    actionStart: "Commencer",
    actionFinish: "Terminer",
    serviceCompleted: "Service terminé",
    experienceQuestion: "Comment s'est passée votre expérience avec",
    writeReview: "Écrire un avis...",
    submitReview: "Soumettre l'avis",
    finishJob: "Générer facture & Terminer",
    onlineNow: "En ligne",
    typeMessage: "Tapez un message...",
    leaveNegotiation: "Quitter la négociation ?",
    leaveNegotiationDesc: "Vous avez une négociation active.",
    returnToMarket: "Retourner au marché",
    stayHere: "Rester ici",
    updateOffer: "Mettre à jour l'offre",
    newPrice: "Nouveau prix",
    reasonChange: "Raison du changement",
    sendUpdate: "Envoyer la mise à jour",
    confirmChange: "Confirmer le changement",
    confirmChangeDesc: "Acceptez-vous le prix de",
    confirmChangeSuffix: " ?",
    yesConfirm: "Oui, confirmer",
    cancel: "Annuler",
    confirmWorkDone: "Le travail est-il terminé ?",
    confirmWorkDoneDesc: "Le pro a marqué le travail comme terminé. Veuillez confirmer.",
    yesFinished: "Oui, terminé",
    noNotYet: "Non, pas encore",
    confirmPayment: "Avez-vous reçu le paiement ?",
    confirmPaymentDesc: "Le client a confirmé. Avez-vous été payé ?",
    yesReceived: "Oui, reçu",
    chatArchived: "Chat archivé",
    reopenChat: "Rouvrir le chat",
    waitingClient: "En attente du client...",
    waitingPayment: "En attente du paiement...",
    liveFeed: "Flux en direct",
    opportunities: "Opportunités",
    liveMarket: "Marché en direct",
    jobClosed: "Travail fermé & archivé.",
    invoiceGen: "Facture générée. En attente de la confirmation du client.",
    chatReopened: "Chat rouvert.",
    statusConfirmed: "Service confirmé",
    subConfirmed: "Le pro a accepté la demande",
    statusEnRoute: "En route",
    subEnRoute: "Le pro se déplace",
    statusArrived: "Arrivé",
    subArrived: "Le pro est sur place",
    statusInProgress: "En cours",
    subInProgress: "Le service est en cours d'exécution",
    statusCompleted: "Terminé",
    subCompleted: "Service terminé",
    personalInfo: "Infos personnelles",
    companyData: "Données de l'entreprise",
    addressLogistics: "Adresse & Logistique",
    security: "Sécurité",
    logisticsNote: "Logistique",
    luxNoteDesc: "Info logistique Luxembourg",
    companyDesc: "Gérez les détails de votre entreprise",
    cantEditHelp: "Certains champs sont en lecture seule",
    legalForm: "Forme juridique",
    govAuth: "Autorisation Gov",
    banking: "Bancaire",
    manageIdentity: "Gérer l'identité",
    languages: "Langues",
    smartAddress: "Adresse intelligente",
    connectPortfolio: "Connecter Instagram",
    connectPortfolioDesc: "Présentez votre travail directement depuis Instagram",
    connecting: "Connexion...",
    connectBtn: "Connecter",
    autoSync: "Synchro Auto",
    instaConnected: "Instagram Connecté",
    itemsSynced: "éléments synchronisés",
    disconnect: "Déconnecter",
    noCaption: "Pas de légende",
    postedOn: "Publié le",
    wantService: "Je veux ce service",
    rating: "Évaluation",
    jobs: "Travaux",
    xp: "XP",
    speaks: "Parle",
    serviceLocation: "Lieu du service",
    openMaps: "Ouvrir Maps",
    bio: "Bio",
    serviceTimeline: "Chronologie",
    hireNow: "Engager maintenant",
    viewInstaBtn: "Voir Portfolio",
    recording: "Enregistrement",
    clientRole: "Client",
    reliableClient: "Fiable",
    requestsMade: "Demandes",
    paymentRate: "Taux de paiement",
    subscription: "Abonnement & Facturation",
    currentPlan: "Plan actuel",
    paymentCard: "Carte de paiement",
    changeCard: "Changer de carte",
    upgradePro: "Passer à PRO",
    upgradeDesc: "Automatisez votre comptabilité avec des factures conformes au Luxembourg.",
    invBillTo: "Facturer à",
    invDate: "Date de facture",
    invDue: "Échéance",
    invDesc: "Description",
    invQty: "Qté",
    invRate: "Taux",
    invTotal: "Total",
    invSubtotal: "Sous-total (HT)",
    invVatAmt: "Montant TVA",
    invTotalDue: "Total Dû (TTC)",
    invFooter: "Paiement dû sous 14 jours.",
    businessHours: "Heures d'ouverture",
    openingTime: "Ouverture",
    closingTime: "Fermeture",
    workingDays: "Jours ouvrables",
    addToFavorites: "Ajouter aux favoris",
    removeFromFavorites: "Retirer des favoris",
    blockContact: "Bloquer l'entreprise",
    unblockContact: "Débloquer",
    blockedUsers: "Utilisateurs bloqués",
    noBlockedUsers: "Aucun utilisateur bloqué.",
    favoritesTab: "Favoris",
    noFavorites: "Pas encore de favoris.",
    contactInfo: "Infos de contact",
    onlinePresence: "En ligne & Social",
    startDate: "De",
    endDate: "À",
    customRange: "Période personnalisée",
    roleLabel: "Rôle :",
    quickAccess: "Accès Rapide (Démo)",
    orLoginManual: "Ou connexion manuelle",
    licenseInfo: "Cette licence est délivrée par le Ministère de l'Économie.",
    uploadPdfLabel: "Télécharger PDF / Photo",
    attached: "Document joint",
    instaPortfolio: "Portfolio Instagram",
    summaryServices: "Services",
    summaryPlan: "Plan",
    summaryIban: "IBAN",
    activePlan: "(Actif)",
    closedDay: "Fermé",
    chatSettings: "Paramètres de chat",
    smartReply: "Réponse intelligente",
    smartReplyDesc: "Réponse automatique lorsque vous êtes occupé ou au volant.",
    activationTime: "Activer si pas de réponse dans :",
    immediate: "Immédiatement",
    mins5: "5 Minutes",
    mins15: "15 Minutes",
    botPersonality: "Personnalité du Bot",
    agilityMode: "Agilité (Priorité Vitesse)",
    agilityDesc: "Informe que vous conduisez et répondrez bientôt.",
    dataMode: "Collecte de Données (Recommandé)",
    dataDesc: "Demande des photos et détails pour accélérer le devis.",
    customMode: "Message Personnalisé",
    customDesc: "Écrivez votre propre message de bienvenue.",
    botMsgFooter: "Réponse auto - Pro notifié.",
    enableAutoReply: "Activer les réponses automatiques",
    preview: "Aperçu",
    yourMessage: "Votre message",
    botMessageAgility: "Bonjour ! Je suis l'assistant virtuel. Le professionnel conduit ou travaille actuellement. Il a reçu votre demande et répondra personnellement dès que possible !",
    botMessageData: "Merci de nous avoir choisis ! Je termine un travail en ce moment. Pour accélérer les choses, pourriez-vous envoyer des photos ou décrire le problème plus en détail ici ? Je répondrai sous peu.",
    botMessageCustomDefault: "Bienvenue ! Je serai avec vous sous peu.",
    financialErp: "Financier (ERP)",
    scanningJobs: "Recherche de travaux...",
    upgradeNow: "Mettre à niveau",
    upgradeBtn: "Mettre à niveau",
    stepIndicator: "Étape {step} sur {total}",
    licenseUploaded: "LICENCE_TELECHARGEE.PDF",
    tagPunctual: "Ponctuel",
    tagClean: "Travail Propre",
    tagPro: "Professionnel",
    tagFriendly: "Amical",
    tagFair: "Prix Juste",
    teamTab: "Mon Équipe",
    addMember: "Inscrire un employé",
    editMember: "Modifier l'employé",
    manageTeam: "Gérer l'équipe",
    manageTeamDesc: "Tableau de bord RH & Opérations Terrain",
    roleTitle: "Rôle / Titre",
    emailLogin: "Email (Connexion)",
    active: "Actif",
    inactive: "Inactif",
    fireStaff: "Désactiver",
    staffAdded: "Membre de l'équipe ajouté",
    staffUpdated: "Dossier employé mis à jour",
    assignTech: "Assigner un technicien",
    assignDesc: "Sélectionnez qui ira sur place.",
    assignedMsg: "L'entreprise a assigné le technicien",
    staffDashboard: "Mes Travaux",
    staffRestriction: "Accès Restreint",
    staffRestrictionDesc: "En tant que membre du personnel, vous n'avez accès qu'à vos travaux assignés et au chat.",
    navToJob: "Naviguer vers le travail",
    completeJob: "Terminer le travail",
    jobCompletedBy: "Travail terminé par le technicien",
    hrNationality: "Nationalité / Origine",
    hrCns: "Matricule CNS",
    hrIdCard: "Carte ID / Passeport",
    hrBirthDate: "Date de Naissance",
    hrDataTab: "RH & Juridique",
    basicDataTab: "Identité",
    deleteStaff: "Supprimer l'employé",
    deleteStaffConfirm: "Êtes-vous sûr de vouloir supprimer cet employé ? Cette action est irréversible.",
    uploadPhoto: "Photo de l'employé",
    saveEmployee: "Enregistrer",
    verifiedBadge: "Employé Vérifié"
};

const translations = {
  EN: enTranslations,
  PT: ptTranslations,
  FR: frTranslations,
  DE: enTranslations, // Fallback to English for brevity, ideally would be German
  LB: frTranslations  // Fallback to French for Luxembourgish (common convention if LB missing)
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof enTranslations;
  tCategory: (catId: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('FR');

  const t = translations[language] || translations['EN'];

  // FIX: Properly look up category translation
  const tCategory = (catId: string) => {
    const langMap = CATEGORY_TRANSLATIONS[language];
    if (langMap && langMap[catId]) {
        return langMap[catId];
    }
    // Fallback to English/ID if not found
    return catId; 
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tCategory }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
